mod ai;
mod auto;
mod backup;
mod classes;
mod conf;
mod door;
mod peers;
mod sample;
mod recover;
mod electrum;
mod health;
mod ipfs;
mod ipfsconf;
mod mining;
mod msg;
mod pass;
mod place;
mod price;
mod refund;
mod issue;
mod ledger;
mod issue2;
mod raven;
mod roles;
mod send;
mod setup;
mod sweep;
mod tunnel;
mod vending;
mod wallet;
mod server;
mod services;
mod shop;
mod upload;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        // The owner token is minted once per run and lives only in memory.
        .manage(server::ServerState::default())
        .invoke_handler(tauri::generate_handler![
            raven::node_status,
            raven::network_state,
            raven::list_assets,
            raven::new_address,
            raven::wallet_balance,
            raven::recent_transactions,
            raven::received_by_address,
            raven::wallet_lock_state,
            ipfs::ipfs_status,
            ipfs::check_alive,
            ipfs::pin_add,
            ipfs::pin_remove,
            ipfs::pin_list,
            ipfs::repo_size,
            ipfs::content_kind,
            ipfs::read_metadata,
            ipfs::open_external,
            issue::validate_name,
            issue::name_taken,
            issue::issue_asset,
            issue2::asset_kinds,
            issue2::reissue,
            issue2::issue_many_unique,
            issue2::issue_qualifier,
            issue2::tag_address,
            issue2::issue_restricted,
            issue2::addresses_with_tag,
            issue2::address_restrictions,
            issue2::freeze,
            issue2::unfreeze,
            issue2::untag_address,
            issue2::tags_for_address,
            issue2::can_receive,
            send::check_address,
            send::address_history,
            send::preview_send,
            send::send_asset,
            send::transfer_ownership,
            send::send_rvn,
            upload::ipfs_add_file,
            upload::ipfs_add_bundle,
            upload::build_metadata,
            shop::list_shops,
            shop::shop_name_free,
            shop::shop_asset_name,
            shop::build_shop_profile,
            shop::build_menu,
            shop::counter_confirmations,
            shop::shop_load,
            shop::shop_save,
            shop::shop_open_now,
            shop::incoming_payments,
            shop::split_payment,
            shop::pay_order,
            shop::broadcast_message,
            ai::save_api_key,
            ai::delete_api_key,
            ai::api_key_status,
            ai::ai_fill,
            ai::ai_answer,
            ai::ai_answer_any,
            ai::ai_chat,
            ai::save_custom_provider,
            ai::model_settings,
            ai::save_model,
            wallet::encryption_state,
            wallet::encrypt_wallet,
            wallet::change_passphrase,
            wallet::unlock_for,
            wallet::lock_wallet,
            vending::sellable_assets,
            vending::pending_sales,
            vending::fulfil_sale,
            auto::auto_fulfil,
            auto::auto_usage,
            auto::auto_enable,
            auto::auto_disable,
            auto::exposure,
            auto::owner_tokens,
            auto::confirmation_policy,
            auto::rebuild_delivered,
            msg::my_channels,
            msg::broadcast,
            msg::inbox,
            msg::subscribe,
            msg::pubsub_ready,
            msg::pubsub_send,
            pass::today_ymd,
            pass::member_number,
            pass::save_member,
            pass::list_members,
            pass::check_in_lookup,
            pass::check_in,
            door::door_list,
            door::door_save,
            door::door_remove,
            door::door_probe,
            door::door_open,
            door::door_log,
            door::open_for_member,
            pass::set_frozen,
            pass::extend,
            pass::add_months,
            pass::period_end,
            pass::add_visits,
            pass::rebuild_members,
            pass::unclaimed_numbers,
            pass::remove_member,
            refund::refund,
            refund::staff_refund,
            ledger::ledger_range,
            ledger::ledger_csv,
            ledger::ledger_export,
            ledger::ledger_pending,
            refund::staff_refund_limits,
            refund::foreign_spends,
            refund::note_our_tx,
            backup::backup_survey,
            backup::backup_now,
            backup::backup_auto,
            backup::backup_zip,
            backup::external_drives,
            backup::cloud_folders,
            sample::sample_check,
            sample::sample_fill,
            sample::sample_clear,
            peers::peer_list,
            peers::peer_add,
            peers::peer_remove,
            peers::pin_my_assets,
            recover::node_identity,
            recover::node_rename,
            recover::restore_survey,
            recover::restore_apply,
            recover::recovery_card,
            recover::recovery_card_print,
            recover::phone_lost_plan,
            recover::backup_folders,
            backup::exclusive_check,
            backup::address_pool,
            backup::reveal_seed,
            mining::mining_reality,
            mining::mining_address,
            mining::mining_income,
            mining::miner_command,
            mining::mining_status,
            mining::miner_start,
            mining::miner_stop,
            mining::miner_running,
            mining::gpu_presets,
            mining::known_pools,
            mining::power_curve,
            mining::detect_gpu,
            mining::mac_miners,
            electrum::electrum_status,
            electrum::wallet_view,
            electrum::chain_address,
            electrum::wallet_send_signed,
            electrum::address_assets,
            electrum::holds_asset,
            ipfsconf::ipfs_options,
            ipfsconf::ipfs_config_read,
            ipfsconf::ipfs_config_write,
            ipfsconf::ipfs_apply_profile,
            ipfsconf::chain_ipfs_link,
            classes::session_save,
            classes::session_list,
            classes::session_book,
            classes::session_cancel,
            classes::session_remove,
            services::services_status,
            services::services_start,
            services::services_stop,
            services::open_shop,
            setup::inspect_machine,
            setup::recommend_setup,
            setup::recommend_setup_for,
            setup::disk_now,
            setup::apply_setup,
            conf::conf_options,
            conf::conf_templates,
            conf::conf_read,
            conf::conf_write,
            health::default_paths,
            health::autostart_status,
            health::autostart_enable,
            health::autostart_disable,
            health::service_health,
            place::parse_coords,
            place::distance_m,
            place::directions_links,
            price::rvn_rate,
            price::quote_price,
            server::start_phone_server,
            server::publish_shop,
            tunnel::tunnel_status,
            tunnel::tunnel_start,
            tunnel::tunnel_stop,
            tunnel::public_base,
            tunnel::open_share,
            tunnel::share_targets,
            server::qr_svg,
            server::rotate_role_token,
            server::logout_all_phones,
            server::remote_admin_get,
            server::remote_admin_set,
            server::table_qr_sheet,
            sweep::sweep_configure,
            sweep::sweep_read,
            sweep::sweep_run,
            sweep::sweep_hold,
            sweep::hours_save,
            sweep::is_open,
            sweep::set_manual,
            roles::role_catalogue,
            roles::role_limits,
            server::publish_offer,
            server::withdraw_offer,
            server::pending_claims,
            server::mark_sent,
            server::load_orders,
            server::order_states,
            server::set_order_state,
        ])
        .build(tauri::generate_context!())
        .expect("error while running tauri application")
        .run(|_app, event| {
            // 앱이 끝나면 채굴기도 끝난다. 이게 없으면 창을 닫은 뒤에도
            // 채굴기가 살아남아 전기를 계속 먹는데, 화면에는 아무것도 없어서
            // 사장은 자기 돈이 나가는 줄 모른다.
            if matches!(event, tauri::RunEvent::Exit) {
                crate::mining::stop_on_exit();
            }
        });
}
