/** 증명서 「한 번에 여러 장」 화면 말 — 한국어 원문 + 영어·일본어·간체 중국어. */
export const CERT_COPY: Record<string, [string, string, string]> = {
  "(왼쪽 위 3×4cm 증명사진)": ["(3×4cm ID photo, top left)", "（左上に 3×4cm の証明写真）", "（左上角 3×4cm 证件照）"],
  "CSV로 받기": ["Get as CSV", "CSVで受け取る", "获取 CSV"],
  "PNG 나 JPG 그림만 넣을 수 있어요.": ["Only PNG or JPG images can be added.", "PNGかJPGの画像だけ追加できます。", "只能添加 PNG 或 JPG 图片。"],
  "{0} / {1}장": ["{0} / {1} sheets", "{0} / {1}枚", "{0} / {1} 张"],
  "{0} 폴더에 저장했어요 · {1} · {2} — 채워서 「표 올리기」로 올려 주세요.": ["Saved to {0} · {1} · {2} — fill one in and upload it with Upload sheet.", "{0} フォルダに保存しました · {1} · {2} — 記入して「表をアップロード」からアップロードしてください。", "已保存到 {0} · {1} · {2} — 填写后用「上传表格」上传。"],
  "등급이 너무 길어요 — {0}자까지 넣을 수 있어요": ["The grade is too long — up to {0} characters.", "等級が長すぎます — {0}文字まで入力できます", "等级太长 — 最多可输入 {0} 个字"],
  "번호가 너무 길어요 — {0}자까지 넣을 수 있어요": ["The number is too long — up to {0} characters.", "番号が長すぎます — {0}文字まで入力できます", "编号太长 — 最多可输入 {0} 个字"],
  "발급일은 {0}년부터 {1}년 사이로 적어 주세요": ["Enter a date issued between {0} and {1}.", "発行日は{0}年から{1}年の間で入力してください", "请填写 {0} 年至 {1} 年之间的颁发日期"],
  "보냈는지 아직 모르는 묶음이 있어요. 기록될 때까지 기다린 뒤 이어서 만들어 주세요.": ["A batch may or may not have been sent yet. Wait until it's recorded, then continue.", "送ったかまだ分からない束があります。記録されるまで待ってから続けてください。", "有一批尚不确定是否已发送。请等到记录完成后再继续。"],
  "{0}명이 넘으면 「표 올리기」로 한 번에 만들 수 있어요(500줄까지, 50장씩 나눠 보내요).": ["For more than {0} people, use Upload sheet to create them all at once (up to 500 rows, sent in batches of 50).", "{0}人を超える場合は「表をアップロード」でまとめて作れます（500行まで、50枚ずつ分けて送ります）。", "超过 {0} 人时，可用「上传表格」一次性创建（最多 500 行，每 50 张分批发送）。"],
  "{0}번에 나눠 보내요": ["Sent in {0} batches", "{0}回に分けて送ります", "分 {0} 批发送"],
  "{0}번에 나눠 보냈어요": ["Sent in {0} batches", "{0}回に分けて送りました", "已分 {0} 批发送"],
  "{0}번째 묶음 · {1}장": ["Batch {0} · {1} sheets", "{0}回目の束 · {1}枚", "第 {0} 批 · {1} 张"],
  "{0}번째 줄 발행": ["Issue row {0}", "{0}行目を発行", "发行第 {0} 行"],
  "{0}번째 줄 사진 고르기": ["Choose a photo for row {0}", "{0}行目の写真を選ぶ", "为第 {0} 行选择照片"],
  "{0}번째 줄과 같아요(받는 사람·과정·발급일)": ["Same as row {0} (recipient, course, date issued)", "{0}行目と同じです（受け取る人・コース・発行日）", "与第 {0} 行相同（收件人、课程、颁发日期）"],
  "{0}장 만들기": ["Create {0} certificates", "{0}枚作る", "创建 {0} 张"],
  "{0}장 중 {1}장을 만들었어요": ["Created {1} of {0} certificates", "{0}枚中{1}枚を作りました", "{0} 张中已创建 {1} 张"],
  "{0}장을 만드는 중이에요": ["Creating {0} certificates", "{0}枚を作っています", "正在创建 {0} 张"],
  "{0}장을 만들었어요": ["Created {0} certificates", "{0}枚作りました", "已创建 {0} 张"],
  "{0}줄 중 {1}장 발행": ["Issue {1} of {0} rows", "{0}行中{1}枚発行", "{0} 行中发行 {1} 张"],
  "— {이름}·{과정} 은 줄마다 바뀌어 들어가요": ["— {name}·{course} change for each row", "— {name}・{course} は行ごとに変わります", "— {name}·{course} 会随每行变化"],
  "— 없음 —": ["— None —", "— なし —", "— 无 —"],
  "「{0}」 {1}장을 만들어요": ["Creating {1} certificates for “{0}”", "「{0}」を{1}枚作ります", "为「{0}」创建 {1} 张"],
  "「{0}」에서 {1}줄을 읽었어요 ({2}초). 이 컴퓨터 안에서만 읽었어요.": ["Read {1} rows from “{0}” ({2}s). Everything was read only on this computer.", "「{0}」から{1}行を読み込みました（{2}秒）。このコンピューターの中だけで読みました。", "从「{0}」读取了 {1} 行（{2} 秒）。全部只在这台电脑上读取。"],
  "「전체 인쇄」는 한 파일에 A4 여러 쪽 — 인쇄 창에서 「PDF로 저장」하면 묶음 PDF 하나가 돼요. 「이 사람만」은 그 사람 한 장만 열어요.": ["“Print all” puts every sheet as A4 pages in one file — choose “Save as PDF” in the print window to get one combined PDF. “This person only” opens just that person's sheet.", "「すべて印刷」は1つのファイルにA4を複数ページ — 印刷ウィンドウで「PDFで保存」すると、まとめたPDFが1つできます。「この人だけ」はその人の1枚だけを開きます。", "「全部打印」会把多页 A4 合成一个文件——在打印窗口选择「存为 PDF」即可生成一份合并 PDF。「仅此人」只打开该人的那一张。"],
  "걸린 시간 {0}초": ["Time taken: {0}s", "かかった時間 {0}秒", "耗时 {0} 秒"],
  "고칠 줄 {0}": ["Rows to fix: {0}", "直す行 {0}", "需修正的行 {0}"],
  "과정": ["Course", "コース", "课程"],
  "과정이 너무 길어요 — {0}자까지 넣을 수 있어요": ["The course name is too long — up to {0} characters.", "コースが長すぎます — {0}文字まで入力できます", "课程名称太长 — 最多可输入 {0} 个字"],
  "그 차례의 증서가 없어요.": ["There is no certificate at that position.", "その順番の証書がありません。", "没有那个顺序对应的证书。"],
  "그림 파일이 아니거나 너무 커요.": ["This isn't an image file, or it's too large.", "画像ファイルでないか、大きすぎます。", "不是图片文件，或文件过大。"],
  "그림을 그리지 못했어요.": ["Could not draw the image.", "画像を描けませんでした。", "无法绘制图片。"],
  "그림을 열지 못했어요. PNG나 JPG로 바꿔서 올려 주세요.": ["Could not open the image. Please convert it to PNG or JPG and upload again.", "画像を開けませんでした。PNGかJPGに変えてアップロードしてください。", "无法打开图片。请转换为 PNG 或 JPG 后再上传。"],
  "그림을 읽지 못했어요.": ["Could not read the image.", "画像を読み込めませんでした。", "无法读取图片。"],
  "기다림": ["Waiting", "待機中", "等待中"],
  "기록을 찾지 못했어요.": ["Could not find the record.", "記録が見つかりませんでした。", "未找到记录。"],
  "기본 예문 · AI가 쓴 글이 아니에요 · 눌러서 본문에 넣어요": ["Default example · Not written by AI · Tap to insert into the text", "基本の例文 · AIが書いた文章ではありません · 押すと本文に入ります", "默认示例 · 并非 AI 撰写 · 点击插入正文"],
  "김하늘\n이바다": ["Jane Smith\nJohn Doe", "山田 花子\n田中 太郎", "王小明\n李小红"],
  "나머지 {0}장 이어서 만들기": ["Continue creating the remaining {0}", "残り{0}枚を続けて作る", "继续创建剩余的 {0} 张"],
  "나머지 {0}장은 안 나갔어요{1}. 이미 만든 줄은 다시 만들지 않아요.": ["The remaining {0} were not issued{1}. Rows already created will not be created again.", "残りの{0}枚は送信されませんでした{1}。すでに作った行は再度作りません。", "剩余 {0} 张未发送{1}。已创建的行不会重复创建。"],
  "도장": ["Seal", "印鑑", "印章"],
  "등급": ["Grade", "等級", "等级"],
  "라비 답에서 쓸 만한 문장을 못 찾았어요 — 기본 예문을 보여 드려요.": ["Couldn't find a usable sentence in Ravi's reply — showing the default example instead.", "Raviの返事から使える文章が見つかりませんでした — 基本の例文を表示します。", "未能从 Ravi 的回复中找到可用的句子 — 显示默认示例。"],
  "라비 제안 · 눌러서 본문에 넣어요 (고쳐 써도 돼요)": ["Ravi's suggestion · Tap to insert into the text (you can edit it)", "Raviの提案 · 押すと本文に入ります（書き直してもいいです）", "Ravi 的建议 · 点击插入正文（可自行修改）"],
  "라비가 {0}줄을 읽어 명단 끝에 붙였어요.": ["Ravi read {0} rows and added them to the end of the roster.", "Raviが{0}行を読み取り、名簿の最後に追加しました。", "Ravi 读取了 {0} 行，并添加到名单末尾。"],
  "라비가 {0}줄을 읽었어요.": ["Ravi read {0} rows.", "Raviが{0}行を読み取りました。", "Ravi 读取了 {0} 行。"],
  "라비가 명단을 읽는 중… (보통 10~30초)": ["Ravi is reading the roster… (usually 10–30 seconds)", "Raviが名簿を読み取っています…（通常10〜30秒）", "Ravi 正在读取名单…（通常需要 10–30 秒）"],
  "라비가 쓰는 중…": ["Ravi is writing…", "Raviが書いています…", "Ravi 正在撰写…"],
  "라비가 확실히 못 읽었어요 — 사진과 맞춰 보세요": ["Ravi couldn't read this clearly — please check it against the photo.", "Raviがはっきり読み取れませんでした — 写真と照らし合わせてください", "Ravi 未能确定读取内容 — 请对照照片核实"],
  "로고나 도장만 넣을 수 있어요.": ["Only a logo or seal can be added.", "ロゴか印鑑だけ追加できます。", "只能添加徽标或印章。"],
  "명단 비우기": ["Clear the roster", "名簿を空にする", "清空名单"],
  "명단 사진 읽기 · 라비": ["Read roster photo · Ravi", "名簿の写真を読む · Ravi", "读取名单照片 · Ravi"],
  "명단 사진은 사진 읽기로 넣어 주세요.": ["Add roster photos using Read photo.", "名簿の写真は「写真を読む」から入れてください。", "请通过「读取照片」添加名单照片。"],
  "명단 사진을 라비에게 보낼까요?": ["Send the roster photo to Ravi?", "名簿の写真をRaviに送りますか？", "要把名单照片发送给 Ravi 吗？"],
  "명단 표(xlsx·xls·csv)나 사진 파일만 읽어요.": ["Only reads a roster sheet (xlsx, xls, csv) or photo files.", "名簿の表（xlsx・xls・csv）か写真ファイルだけ読み込みます。", "只读取名单表格（xlsx、xls、csv）或照片文件。"],
  "명단 표·사진을 확인 표에 넣어요": ["Add roster sheets or photos to the review table", "名簿の表・写真を確認表に入れます", "将名单表格或照片加入核对表"],
  "명단 표를 확인해 주세요.": ["Please check the roster sheet.", "名簿の表を確認してください。", "请检查名单表格。"],
  "명단을 비울까요?": ["Clear the roster?", "名簿を空にしますか？", "要清空名单吗？"],
  "문구 도와줘 · 라비": ["Help with wording · Ravi", "文章を手伝って · Ravi", "帮忙写文案 · Ravi"],
  "미리보기 · {0}번째 줄 · 표에서 줄을 누르면 그 사람으로 바뀌어요": ["Preview · Row {0} · Tap a row in the table to switch to that person", "プレビュー · {0}行目 · 表の行を押すとその人に切り替わります", "预览 · 第 {0} 行 · 点击表格中的行即可切换到该人"],
  "받는 사람": ["Recipient", "受け取る人", "收件人"],
  "받는 사람 (한 줄에 한 명 · 엑셀에서 여러 칸을 복사해 붙여도 돼요)": ["Recipients (one per line · you can also copy and paste multiple cells from Excel)", "受け取る人（1行に1人 · エクセルから複数のセルをコピーして貼り付けてもいいです）", "收件人（每行一人 · 也可以从 Excel 复制多个单元格粘贴）"],
  "받는 사람 열을 찾지 못했어요. 위에서 어느 열이 받는 사람인지 골라 주세요.": ["Couldn't find the recipient column. Please choose which column is the recipient above.", "受け取る人の列が見つかりませんでした。上でどの列が受け取る人か選んでください。", "未能找到收件人所在的列。请在上方选择哪一列是收件人。"],
  "받는 사람 이름·사진은 확인 페이지(/verify)에 나오지 않아요. 번호와 QR로 진짜인지만 확인해요.": ["Recipient names and photos do not appear on the check page (/verify). Only the number and QR are used to confirm it's genuine.", "受け取る人の名前・写真は確認ページ（/verify）には表示されません。番号とQRだけで本物かを確認します。", "收件人姓名和照片不会出现在查验页面（/verify）上。只用编号和二维码确认真伪。"],
  "받는 사람·과정·사진은 체인에 올리지 않아요. 인쇄하는 종이와 이 컴퓨터에만 남아요.": ["Recipient, course and photo are not put on the chain. They stay only on the printed paper and this computer.", "受け取る人・コース・写真はチェーンに載せません。印刷した紙とこのコンピューターにだけ残ります。", "收件人、课程和照片不会上链，只保留在打印的纸张和这台电脑上。"],
  "받는 사람이 너무 길어요 — {0}자까지 넣을 수 있어요": ["The recipient name is too long — up to {0} characters.", "受け取る人が長すぎます — {0}文字まで入力できます", "收件人姓名太长 — 最多可输入 {0} 个字"],
  "받는 사람이 비어 있어요": ["The recipient is empty", "受け取る人が空です", "收件人为空"],
  "발급일을 알아볼 수 없어요 (예: 2026-09-24)": ["Couldn't recognize the date issued (e.g. 2026-09-24)", "発行日を認識できません（例: 2026-09-24）", "无法识别颁发日期（例如 2026-09-24）"],
  "발급처 로고": ["Issuer logo", "発行元ロゴ", "发行方徽标"],
  "발행": ["Issue", "発行", "发行"],
  "발행할 줄이 없어요. 확인 표에서 받는 사람을 채우거나 발행 체크를 켜 주세요.": ["No rows to issue. Fill in a recipient in the review table, or turn on the issue checkbox.", "発行する行がありません。確認表で受け取る人を入力するか、発行のチェックをオンにしてください。", "没有可发行的行。请在核对表中填写收件人，或勾选发行复选框。"],
  "발행할 증서": ["Certificates to issue", "発行する証書", "待发行的证书"],
  "방금 창에 놓은 파일만 읽을 수 있어요.": ["Only the file you just dropped in this window can be read.", "たった今このウィンドウに置いたファイルだけ読み込めます。", "只能读取刚刚放到此窗口的文件。"],
  "방금 창에 놓은 폴더만 읽을 수 있어요.": ["Only the folder you just dropped in this window can be read.", "たった今このウィンドウに置いたフォルダだけ読み込めます。", "只能读取刚刚放到此窗口的文件夹。"],
  "번호": ["Number", "番号", "编号"],
  "번호 목록 표 받기 (엑셀)": ["Get the number list sheet (Excel)", "番号一覧の表を受け取る（エクセル）", "获取编号列表表格（Excel）"],
  "번호 목록 표를 열었어요. 받는 사람 이름이 든 파일이라 먼저 이 컴퓨터의 앱 폴더에 만들었어요 — 열린 프로그램에서 원하는 곳에 저장해 주세요.": ["Opened the number list sheet. Since this file contains recipient names, it was first created in this computer's app folder — please save it wherever you like from the program that opened it.", "番号一覧の表を開きました。受け取る人の名前が入るファイルのため、まずこのコンピューターのアプリフォルダに作成しました — 開いたプログラムから好きな場所に保存してください。", "已打开编号列表表格。由于该文件含有收件人姓名，先在这台电脑的应用文件夹中创建 — 请在打开的程序中另存到您想要的位置。"],
  "보내고 읽기": ["Send and read", "送って読む", "发送并读取"],
  "본문 (선택)": ["Body text (optional)", "本文（任意）", "正文（可选）"],
  "붙여 넣은 {0}줄을 확인 표로 옮겼어요.": ["Moved the {0} pasted rows into the review table.", "貼り付けた{0}行を確認表に移しました。", "已将粘贴的 {0} 行移入核对表。"],
  "비고": ["Note", "備考", "备注"],
  "비웁니다": ["Clear it", "空にします", "清空"],
  "빼기": ["Remove", "外す", "移除"],
  "뺀 줄 {0}": ["Rows excluded: {0}", "除外した行 {0}", "已排除的行 {0}"],
  "사진 {0}장": ["{0} photos", "写真{0}枚", "{0} 张照片"],
  "사진 {0}장을 받았어요. 이제 명단(표 올리기·받는 사람 칸)을 넣으면 파일 이름으로 짝지어요.": ["Received {0} photos. Now add the roster (Upload sheet or the Recipient field) and they'll be matched by file name.", "写真{0}枚を受け取りました。名簿（表をアップロード・受け取る人欄）を入れると、ファイル名で照合します。", "已收到 {0} 张照片。接下来添加名单（上传表格或收件人栏），会按文件名自动匹配。"],
  "사진 {0}장을 짝지었어요 ({1}초). 사진은 이 컴퓨터 밖으로 안 나가요.": ["Matched {0} photos ({1}s). Photos never leave this computer.", "写真{0}枚を照合しました（{1}秒）。写真はこのコンピューターの外に出ません。", "已匹配 {0} 张照片（{1} 秒）。照片不会离开这台电脑。"],
  "사진 {0}장을 함께 인쇄해요 · 사진은 이 컴퓨터에만 둬요.": ["{0} photos will be printed together · Photos stay only on this computer.", "写真{0}枚を一緒に印刷します · 写真はこのコンピューターにだけ置きます。", "将一起打印 {0} 张照片 · 照片只保留在这台电脑上。"],
  "사진 맞추는 중… {0}/{1}": ["Matching photos… {0}/{1}", "写真を照合中… {0}/{1}", "正在匹配照片… {0}/{1}"],
  "사진 없음 — 사진 칸이 빈 채로 인쇄돼요": ["No photo — the photo box will print empty", "写真なし — 写真欄は空のまま印刷されます", "没有照片 — 照片栏将空白打印"],
  "사진 칸 쓰기": ["Use the photo box", "写真欄を使う", "使用照片栏"],
  "사진 파일(JPG·PNG·HEIC)을 골라 주세요.": ["Please choose a photo file (JPG, PNG, HEIC).", "写真ファイル（JPG・PNG・HEIC）を選んでください。", "请选择照片文件（JPG、PNG、HEIC）。"],
  "사진 파일만 읽어요.": ["Only reads photo files.", "写真ファイルだけ読み込みます。", "只读取照片文件。"],
  "사진 파일명": ["Photo file name", "写真ファイル名", "照片文件名"],
  "사진 파일명이 비어 있어요": ["The photo file name is empty", "写真ファイル名が空です", "照片文件名为空"],
  "사진 폴더": ["Photo folder", "写真フォルダ", "照片文件夹"],
  "사진 한꺼번에": ["Multiple photos", "写真をまとめて", "多张照片"],
  "사진에서 명단을 찾지 못했어요.": ["Could not find a roster in the photo.", "写真から名簿を見つけられませんでした。", "未能从照片中识别出名单。"],
  "사진을 읽지 못했어요({0}) — JPG·PNG로 바꿔 주세요": ["Could not read the photo ({0}) — please convert it to JPG or PNG", "写真を読み込めませんでした（{0}） — JPG・PNGに変えてください", "无法读取照片（{0}）— 请转换为 JPG 或 PNG"],
  "사진이 너무 커요.": ["The photo is too large.", "写真が大きすぎます。", "照片过大。"],
  "사진이 받는 사람보다 많아요.": ["There are more photos than recipients.", "写真が受け取る人より多いです。", "照片数量多于收件人。"],
  "샘플 파일 이름이 올바르지 않아요.": ["The sample file name is not valid.", "サンプルファイル名が正しくありません。", "示例文件名无效。"],
  "샘플 표 받기": ["Get sample sheet", "サンプル表を受け取る", "获取示例表格"],
  "서명 칸 위에 찍혀요": ["Stamped over the signature box", "サイン欄の上に押されます", "盖在签名栏上方"],
  "설정에서 AI 열쇠를 넣으면 라비가 제목에 맞춰 새로 써 드려요.": ["If you add an AI key in Settings, Ravi will write new wording to match the title.", "設定でAIキーを入れると、Raviがタイトルに合わせて新しく書いてくれます。", "在设置中填入 AI 密钥后，Ravi 会根据标题重新撰写文案。"],
  "설정에서 AI 열쇠를 넣으면 라비가 종이 명단·출석부 사진을 읽어 확인 표에 넣어 드려요. 사진은 누를 때 한 번, 고른 AI로만 가요.": ["If you add an AI key in Settings, Ravi will read photos of paper rosters or attendance sheets and add them to the review table. The photo is sent once, only to the AI provider you chose, each time you tap it.", "設定でAIキーを入れると、Raviが紙の名簿・出席簿の写真を読み取って確認表に入れてくれます。写真は押すたびに一度だけ、選んだAIにだけ送られます。", "在设置中填入 AI 密钥后，Ravi 会读取纸质名单或点名表的照片并加入核对表。照片仅在每次点击时发送一次，只发给您选择的 AI。"],
  "아래 확인 표에서 고치고, 뺄 줄은 체크를 끄세요. 오류가 있는 줄은 저절로 빠져요.": ["Fix entries in the review table below, and uncheck any rows you want to exclude. Rows with errors are excluded automatically.", "下の確認表で直し、除外する行はチェックを外してください。エラーのある行は自動的に除外されます。", "在下方核对表中修改，需排除的行请取消勾选。有错误的行会自动排除。"],
  "안 나감": ["Not sent", "未送信", "未发送"],
  "알 수 없는 작업입니다.": ["Unknown task.", "不明な作業です。", "未知的操作。"],
  "알 수 없는 파일이에요.": ["Unknown file.", "不明なファイルです。", "未知的文件。"],
  "어느 열이 받는 사람인가요? 열을 골라 주세요.": ["Which column is the recipient? Please choose a column.", "どの列が受け取る人ですか？列を選んでください。", "哪一列是收件人？请选择一列。"],
  "엑셀·CSV 명단, 사진 여러 장이나 사진 폴더를 놓으면 확인 표에 넣어요(사진은 파일 이름으로 짝지어요). 문서 한 개는 지문만 적어요. 어디에도 올리지 않아요.": ["Drop an Excel or CSV roster, multiple photos, or a photo folder to add them to the review table (photos are matched by file name). A single document only has its fingerprint written. Nothing is uploaded anywhere.", "エクセル・CSVの名簿、複数の写真、写真フォルダを置くと確認表に入れます（写真はファイル名で照合します）。文書1つは指紋だけを記します。どこにもアップロードしません。", "放入 Excel、CSV 名单、多张照片或照片文件夹即可加入核对表（照片按文件名匹配）。单个文档只记录指纹，不会上传到任何地方。"],
  "엑셀로 열기": ["Open in Excel", "エクセルで開く", "用 Excel 打开"],
  "여러 장을 보내는 중이에요. 끝난 뒤에 문서를 다시 놓아 주세요.": ["Sending multiple sheets. Please drop the document again once this finishes.", "複数枚を送信しています。終わってからもう一度文書を置いてください。", "正在发送多张。请等完成后再重新放入文档。"],
  "열 다시 맞추기": ["Remap columns", "列を合わせ直す", "重新对应列"],
  "열 이름이 달라도 여기서 맞추면 돼요. 열을 바꾸면 표에서 고친 칸은 처음 값으로 돌아가요.": ["Even if the column names differ, you can match them here. Changing a column resets any edited cells in the table to their original values.", "列の名前が違っても、ここで合わせれば大丈夫です。列を変えると、表で直したセルは最初の値に戻ります。", "即使列名不同，也可以在这里对应。更改列后，表格中已修改的单元格会恢复为原始值。"],
  "올렸어요 · 다음에 만들 때도 써요": ["Uploaded · Also used the next time you create", "アップロードしました · 次に作るときも使います", "已上传 · 下次创建时也会使用"],
  "올렸어요 · 서명 칸 위에 찍혀요": ["Uploaded · Stamped over the signature box", "アップロードしました · サイン欄の上に押されます", "已上传 · 盖在签名栏上方"],
  "올린 사진 중에 이 줄의 사진 파일이 없어요": ["None of the uploaded photos match this row's photo file", "アップロードした写真の中に、この行の写真ファイルがありません", "已上传的照片中没有此行对应的照片文件"],
  "이 사람만": ["This person only", "この人だけ", "仅此人"],
  "이 사진 한 장이 이 컴퓨터 밖, 설정에서 고른 AI({0})로 한 번 나가요. 읽은 이름은 확인 표로 들어가요 — 틀릴 수 있으니 꼭 사진과 맞춰 보세요.": ["This one photo will leave this computer once, sent to the AI you chose in Settings ({0}). The names it reads go into the review table — it can be wrong, so please check it against the photo.", "この写真1枚が、このコンピューターの外、設定で選んだAI（{0}）へ一度だけ送られます。読み取った名前は確認表に入ります — 間違うこともあるので、必ず写真と照らし合わせてください。", "这一张照片会离开这台电脑一次，发送给您在设置中选择的 AI（{0}）。识别出的姓名会填入核对表——可能有误，请务必对照照片核实。"],
  "이름 등록이 아직 기록되지 않았어요. 1~2분 뒤에 다시 눌러 주세요.": ["The name registration hasn't been recorded yet. Please press again in 1–2 minutes.", "名前の登録がまだ記録されていません。1〜2分後にもう一度押してください。", "名称注册尚未记录。请 1–2 分钟后再试。"],
  "이름이 같은 사진이 여러 장이에요 — 사진을 눌러 골라 주세요": ["There are multiple photos with the same name — tap to choose one.", "同じ名前の写真が複数あります — 写真を押して選んでください", "有多张同名照片 — 请点击选择"],
  "이름이 길어서 증서에서 글자가 작아져요": ["The name is long, so the text will shrink on the certificate", "名前が長いため、証書の文字が小さくなります", "姓名较长，证书上的文字会缩小"],
  "이미 발행 {0}": ["Already issued {0}", "発行済み {0}", "已发行 {0}"],
  "이미 발행했어요 · {0}": ["Already issued · {0}", "発行済みです · {0}", "已发行 · {0}"],
  "인쇄할 기록이 없어요.": ["There is nothing to print.", "印刷する記録がありません。", "没有可打印的记录。"],
  "전체 인쇄 · PDF로 저장 ({0}장)": ["Print all · Save as PDF ({0} sheets)", "すべて印刷 · PDFで保存（{0}枚）", "全部打印 · 存为 PDF（{0} 张）"],
  "좋아요": ["OK", "OK", "正常"],
  "지갑 잔액": ["Wallet balance", "ウォレット残高", "钱包余额"],
  "지우지 못했어요.": ["Could not delete.", "削除できませんでした。", "无法删除。"],
  "짝 없는 사진 {0}장: {1}": ["{0} unmatched photos: {1}", "組のない写真{0}枚: {1}", "未匹配的照片 {0} 张：{1}"],
  "창을 닫지 마세요 — 50장씩 나눠 보내요. 한 묶음에 보통 몇 초, 노드가 바쁘면 더 걸려요.": ["Don't close this window — sent in batches of 50. Each batch usually takes a few seconds, longer if the node is busy.", "ウィンドウを閉じないでください — 50枚ずつ分けて送ります。1つの束につき通常数秒、ノードが忙しいともっとかかります。", "请不要关闭窗口 — 将按每批 50 张分批发送。每批通常需要几秒，节点繁忙时会更久。"],
  "처음 한 번은 이름 등록이 먼저예요 — 등록과 함께 첫 {0}장을 만들고, 기록되면(1~2분) 「나머지 이어서 만들기」로 {1}장을 더 만들어요.": ["The first time, name registration comes first — the first {0} are created together with the registration, and once it's recorded (1–2 minutes), use Continue with the rest to create {1} more.", "初回だけ名前の登録が先です — 登録と一緒に最初の{0}枚を作り、記録されたら（1〜2分）「残りを続けて作る」で残り{1}枚を作ります。", "第一次需要先注册名称 — 注册的同时创建前 {0} 张，记录完成后（1–2 分钟），用「继续创建剩余」再创建 {1} 张。"],
  "체인 수수료 합계": ["Total chain fees", "チェーン手数料の合計", "链上手续费合计"],
  "투명 PNG · 한 번 올리면 다음에도 써요": ["Transparent PNG · Upload once and it's used next time too", "透過PNG · 一度アップロードすれば次回も使います", "透明 PNG · 上传一次，下次也会使用"],
  "틀릴 수 있으니 사진과 한 번 맞춰 보세요.": ["It can be wrong, so please check it against the photo.", "間違うこともあるので、一度写真と照らし合わせてください。", "可能有误，请对照照片核实一次。"],
  "파일 이름이 올바르지 않아요.": ["The file name is not valid.", "ファイル名が正しくありません。", "文件名无效。"],
  "파일을 찾지 못했어요.": ["Could not find the file.", "ファイルが見つかりませんでした。", "未找到文件。"],
  "파일이 너무 커요.": ["The file is too large.", "ファイルが大きすぎます。", "文件过大。"],
  "파일이 아니에요.": ["This is not a file.", "ファイルではありません。", "这不是文件。"],
  "폴더가 아니에요.": ["This is not a folder.", "フォルダではありません。", "这不是文件夹。"],
  "폴더를 읽지 못했어요.": ["Could not read the folder.", "フォルダを読み込めませんでした。", "无法读取文件夹。"],
  "표 올리기": ["Upload sheet", "表をアップロード", "上传表格"],
  "표를 읽는 중…": ["Reading the sheet…", "表を読み込み中…", "正在读取表格…"],
  "한 번에 기록 20건까지 묶어 인쇄할 수 있어요.": ["You can print up to 20 records together at once.", "一度に記録20件までまとめて印刷できます。", "一次最多可合并打印 20 条记录。"],
  "한 장에 {0} RVN이 체인에 태워지고, 보낼 때마다 네트워크 수수료가 조금 붙어요 · {1}번에 나눠 보내요(한 번에 {2}장까지).": ["{0} RVN is burned on the chain per sheet, plus a small network fee each time something is sent · Sent in {1} batches (up to {2} per batch).", "1枚につき{0} RVNがチェーンで焼却され、送るたびに少しネットワーク手数料がかかります · {1}回に分けて送ります（1回に{2}枚まで）。", "每张会在链上销毁 {0} RVN，每次发送还会产生少量网络手续费 · 将分 {1} 批发送（每批最多 {2} 张）。"],
  "한 폴더에 사진 600장까지 읽어요.": ["Reads up to 600 photos from one folder.", "1つのフォルダにつき写真600枚まで読み込みます。", "每个文件夹最多读取 600 张照片。"],
  "확실히 못 읽은 줄 {0}개는 노란 표시 — 사진과 맞춰 고쳐 주세요.": ["{0} rows that couldn't be read with certainty are marked yellow — check them against the photo and fix them.", "はっきり読み取れなかった{0}行は黄色で表示 — 写真と照らし合わせて直してください。", "有 {0} 行未能确定读取内容，以黄色标示 — 请对照照片修正。"],
  "확인 표와 짝지은 사진이 화면에서 지워져요. 올린 파일은 그대로예요.": ["The review table and matched photos are cleared from the screen. Uploaded files remain untouched.", "確認表と照合した写真が画面から消えます。アップロードしたファイルはそのままです。", "核对表和已匹配的照片会从屏幕上清除，已上传的文件保持不变。"],
  "보냈어요": ["Sent", "送信済み", "已发送"],
  "보냈는지 모름": ["Unknown if sent", "送信したか不明", "不确定是否已发送"],
  "다운로드 폴더에 샘플 파일을 만들지 못했어요.": ["Couldn't create the sample file in the Downloads folder.", "ダウンロードフォルダにサンプルファイルを作れませんでした。", "无法在下载文件夹中创建示例文件。"],
  "방금 받은 샘플 파일만 열 수 있어요.": ["Only the sample file you just got can be opened.", "たった今受け取ったサンプルファイルだけ開けます。", "只能打开刚刚获取的示例文件。"],
  "티켓은 인쇄 대신 판매 링크와 QR을 써요.": ["Tickets use a sales link and QR code instead of printing.", "チケットは印刷の代わりに販売リンクとQRを使います。", "门票不打印，改用销售链接和二维码。"],
};
