export const companionCopy = {
  title: ['라비 · 트레이와 알림','Ravi · tray and notifications','ラビ · トレイと通知','拉比 · 托盘与通知'],
  intro: ['라비는 트레이에 있어요. 필요할 때만 나타나요. 창을 닫아도 앱은 계속 켜져 있어요.','Ravi lives in the tray and appears only when needed. Closing the window keeps the app running.','ラビはトレイにいます。必要なときだけ現れます。ウィンドウを閉じてもアプリは動作します。','拉比在托盘中，需要时才会出现。关闭窗口后应用仍在运行。'],
  always: ['항상 떠 있는 라비 (기본 꺼짐)','Always show Ravi (off by default)','ラビを常に表示（初期設定はオフ）','始终显示拉比（默认关闭）'],
  start: ['다음 실행은 트레이에서 시작','Start in the tray next time','次回はトレイで起動','下次启动到托盘'],
  size: ['캐릭터 크기','Character size','キャラクターの大きさ','角色大小'],
  small: ['작게','Small','小','小'], normal: ['보통','Medium','中','中'], large: ['크게','Large','大','大'],
  quietStart: ['조용한 시간 시작 (시)','Quiet hours start (hour)','通知を控える開始時刻（時）','免打扰开始（时）'],
  quietEnd: ['조용한 시간 끝 (시, 시작과 같으면 끔)','Quiet hours end (same hour disables)','通知を控える終了時刻（同時刻で無効）','免打扰结束（与开始相同则关闭）'],
  limit: ['하루 알림 횟수 (0이면 끔)','Daily notification limit (0 disables)','1日の通知上限（0で無効）','每日通知上限（0则关闭）'],
  reduced: ['움직임 줄이기','Reduce motion','動きを減らす','减少动态效果'],
  greeting: ['시작 인사','Startup greeting','起動時のあいさつ','启动问候'],
  sound: ['작은 효과음','Quiet sound effects','小さな効果音','轻柔音效'],
  battery: ['전력 절약','Save power','省電力','节能'],
  save: ['설정 저장','Save settings','設定を保存','保存设置'],
  saved: ['저장했어요.','Saved.','保存しました。','已保存。'],
  failed: ['라비 설정을 적용하지 못했어요. 트레이에서 큰 화면을 열어 주세요.','Could not apply Ravi settings. Open the main window from the tray.','ラビの設定を適用できません。トレイからメイン画面を開いてください。','无法应用拉比设置，请从托盘打开主窗口。'],
  shortcut: ['전역 단축키는 아직 지원하지 않아요. 트레이의 라비를 눌러 불러 주세요.','Global shortcuts are not available yet. Click Ravi in the tray.','グローバルショートカットは未対応です。トレイのラビを押してください。','暂不支持全局快捷键，请点击托盘中的拉比。'],
  today: ['오늘은 그만','No more today','今日は通知しない','今天不再提醒'],
  close: ['말풍선 닫기','Close bubble','吹き出しを閉じる','关闭气泡'],
  bird: ['라비에게 말하기 · 끌어서 이동','Talk to Ravi · drag to move','ラビに話す · ドラッグで移動','与拉比交谈 · 拖动移动'],
  bubble: ['라비 말풍선','Ravi speech bubble','ラビの吹き出し','拉比消息气泡'],
  ask: ['라비에게 물어보기','Ask Ravi','ラビに質問','询问拉比'],
  send: ['보내기','Send','送信','发送'],
  mic: ['말로 묻기','Ask by voice','声で質問','语音提问'],
  main: ['큰 화면에서 계속하기','Continue in the main window','メイン画面で続ける','在主窗口中继续'],
  settings: ['라비 설정','Ravi settings','ラビの設定','拉比设置'],
  call: ['불렀나요? 무엇을 도와드릴까요?','You called? How can I help?','お呼びですか？何をお手伝いしましょう？','您叫我吗？需要什么帮助？'],
  deposit: ['입금이 도착했어요. 큰 화면에서 확인해 주세요.','A payment arrived. Check the main window.','入金が届きました。メイン画面で確認してください。','收到入款，请在主窗口中查看。'],
  order: ['새 상점 주문이 있어요. 큰 화면에서 확인해 주세요.','There is a new shop order. Check the main window.','新しい注文があります。メイン画面で確認してください。','商店有新订单，请在主窗口中查看。'],
  backup: ['백업을 확인해 주세요. 큰 화면에서 도와드릴게요.','Please check your backup. I can help in the main window.','バックアップを確認してください。メイン画面でお手伝いします。','请检查备份，我会在主窗口中帮助您。'],
  hello: ['안녕하세요. 필요하면 트레이에서 불러 주세요.','Hello. Call me from the tray when needed.','こんにちは。必要なときにトレイから呼んでください。','您好，需要时请从托盘呼叫我。'],
  secret: ['비밀 정보는 대화창에 넣지 마세요. 설정의 전용 입력칸을 사용해 주세요.','Do not put secrets in chat. Use the dedicated field in Settings.','秘密情報を会話に入力しないでください。設定の専用欄を使ってください。','请勿在聊天中输入机密信息，请使用设置中的专用输入框。'],
  idle: ['곁에 있어요.','I am here.','そばにいます。','我在这里。'],
  joy: ['좋은 소식이 왔어요!','Good news!','うれしいお知らせです！','有好消息！'],
  sleepy: ['조금 졸려요…','A little sleepy…','少し眠いです…','有点困了…'],
  surprised: ['앗, 깜짝이야!','Oh, a surprise!','あっ、びっくり！','哎呀，吓了一跳！'],
  focused: ['듣고 있어요.','I am listening.','聞いています。','我在听。'],
  thinking: ['생각 중이에요…','Thinking…','考えています…','正在思考…'],
  working: ['확인 중이에요…','Checking…','確認しています…','正在检查…'],
  sleep: ['잠든 라비 · 눌러서 불러 주세요.','Sleeping Ravi · click to call.','眠るラビ · 押して呼んでください。','睡着的拉比 · 点击呼叫。'],
} as const;
export type CopyKey=keyof typeof companionCopy;
export function copy(key:CopyKey,locale:string='ko'):string {return companionCopy[key][({ko:0,en:1,ja:2,zh:3} as Record<string,number>)[locale]??1];}
