/** 「만들기」 화면 말 — 한국어 원문 + 영어·일본어·간체 중국어. 폰(RavenVault)과 같은 번역을 쓴다. */
export const CREATE_COPY: Record<string, [string, string, string]> = {
  "1부터 {0}까지 적어 주세요.": ["Enter a number from 1 to {0}.", "1から{0}までの数を入力してください。", "请输入 1 到 {0} 之间的数字。"],
  "512MB 이하 파일만 붙일 수 있어요.": ["Only files up to 512 MB can be attached.", "512MB以下のファイルだけ添付できます。", "只能附加 512 MB 以内的文件。"],
  "{0} RVN이 더 필요해요 · 지갑 화면의 받기 주소로 다른 지갑이나 거래소에서 보내 주세요.": ["You need {0} more RVN · Send it to the receive address on the Wallet screen from another wallet or an exchange.", "あと {0} RVN 必要です · ウォレット画面の受け取りアドレスに、ほかのウォレットや取引所から送ってください。", "还需要 {0} RVN · 请从其他钱包或交易所发送到钱包页面的接收地址。"],
  "{0} 외 {1}장": ["{0} and {1} more", "{0} ほか {1}枚", "{0} 等另外 {1} 张"],
  "‹ 이전": ["‹ Previous", "‹ 前へ", "‹ 上一个"],
  "다음 ›": ["Next ›", "次へ ›", "下一个 ›"],
  "← 자산": ["← Assets", "← 資産", "← 资产"],
  "공연·수업·입장권. 여러 장을 한 번에 만들어 나눠 줘요.": ["Shows, classes, admission. Make many at once and hand them out.", "公演・レッスン・入場券。まとめて作って配れます。", "演出、课程、门票。一次做很多张分发出去。"],
  "그림·음악·사진. 한정판 몇 장을 만들어 원본을 증명해요.": ["Art, music, photos. Make a limited edition that proves the original.", "絵・音楽・写真。限定版を作ってオリジナルを証明します。", "画作、音乐、照片。制作限量版，证明原作。"],
  "기록 기다리는 중": ["Waiting for the record", "記録を待っています", "等待记录"],
  "기록 완료 · 이제 마저 만들면 돼요.": ["Recorded · Now just finish creating.", "記録済み · あとは作成を仕上げるだけです。", "已记录 · 现在完成创建即可。"],
  "노드 지갑을 읽지 못했습니다: {0}": ["Could not read the node wallet: {0}", "ノードのウォレットを読めませんでした: {0}", "无法读取节点钱包：{0}"],
  "누구 이름으로": ["Under which name", "だれの名前で", "用谁的名义"],
  "다른 것 고르기": ["Choose something else", "ほかのものを選ぶ", "选择其他"],
  "다시 확인하기": ["Check again", "もう一度確認", "再次检查"],
  "두 번 진행해요. 먼저 이름 등록, 기록된 뒤에 만들기.": ["This happens in two steps: first the name is registered, then the items are created once it is recorded.", "2回に分けて進みます。まず名前の登録、記録されたあとに作成です。", "分两步进行：先注册名称，记录后再创建。"],
  "등록할 이름": ["Name to register", "登録する名前", "要注册的名称"],
  "링크 복사": ["Copy link", "リンクをコピー", "复制链接"],
  "링크를 복사했어요.": ["Link copied.", "リンクをコピーしました。", "链接已复制。"],
  "마저 만들기": ["Finish creating", "作成を続ける", "继续创建"],
  "만드는 사람 이름 (예: 홍길동, 한빛 필라테스)": ["Creator name (e.g. Hong Gildong, Hanbit Pilates)", "作る人の名前（例: Hong Gildong、ハンビット・ピラティス）", "创作者名称（例如 Hong Gildong、韩光普拉提）"],
  "만드는 사람 이름을 영문이나 한글로 3자 이상 적어 주세요.": ["Enter a creator name of at least 3 letters (Latin or Korean).", "作る人の名前を英字かハングルで3文字以上入力してください。", "请用拉丁字母或韩文输入至少 3 个字的创作者名称。"],
  "만들기": ["Create", "作る", "创建"],
  "만들었어요": ["Created", "作成しました", "已创建"],
  "몇 장": ["How many", "何枚", "几张"],
  "무엇을 만드는지 제목을 적어 주세요.": ["Enter a title for what you are creating.", "作るもののタイトルを入力してください。", "请填写要创建内容的标题。"],
  "받기 주소 보기": ["Show receive address", "受け取りアドレスを見る", "查看接收地址"],
  "받는 사람에게 이 한 장을 보내려면 지갑 화면의 「자산 보내기」를 써요.": ["To give this one to someone, use Send assets on the Wallet screen.", "この1枚を相手に送るには、ウォレット画面の「資産を送る」を使います。", "要把这一张发给对方，请使用钱包页面的“发送资产”。"],
  "받는 사람에게 티켓을 보내려면 지갑 화면의 「자산 보내기」를 써요.": ["To give tickets to someone, use Send assets on the Wallet screen.", "チケットを相手に送るには、ウォレット画面の「資産を送る」を使います。", "要把门票发给对方，请使用钱包页面的“发送资产”。"],
  "보통 1~2분, 길면 10분쯤 걸려요. 창을 닫아도 괜찮아요 — 다시 열면 여기서 이어서 해요.": ["Usually 1–2 minutes, up to about 10. You can close the window — it picks up here when you return.", "ふつう1〜2分、長くて10分ほどです。ウィンドウを閉じても大丈夫、次に開くとここから続けます。", "通常 1–2 分钟，最长约 10 分钟。可以关闭窗口，下次打开会从这里继续。"],
  "복사하지 못했어요. QR을 보여 주세요.": ["Could not copy. Show the QR instead.", "コピーできませんでした。QRを見せてください。", "无法复制，请出示二维码。"],
  "붙인 파일 · {0} · 원본은 이 컴퓨터에 두고, 지문만 체인에 새겨요.": ["Attached · {0} · The original stays on this computer; only its fingerprint goes on the chain.", "添付 · {0} · 元のファイルはこのコンピューターに置き、指紋だけをチェーンに刻みます。", "已附加 · {0} · 原件留在这台电脑上，只把指纹写入链上。"],
  "블록에 기록되면 누구나 이 링크로 진짜인지 확인할 수 있어요. 보통 1~2분 걸려요.": ["Once it is in a block, anyone can check it is genuine with this link. Usually 1–2 minutes.", "ブロックに記録されると、だれでもこのリンクで本物か確認できます。ふつう1〜2分です。", "写入区块后，任何人都能用这个链接确认真伪。通常需要 1–2 分钟。"],
  "사진·파일 붙이기 (선택)": ["Attach a photo or file (optional)", "写真・ファイルを添付（任意）", "附加照片或文件（可选）"],
  "수료증·상장·보증서. 한 장에 하나씩, 진짜인지 누구나 확인해요.": ["Course certificates, awards, warranties. One each, and anyone can check it is genuine.", "修了証・賞状・保証書。1枚ずつ、だれでも本物か確認できます。", "结业证书、奖状、保修单。每张一份，任何人都能确认真伪。"],
  "영문이나 한글로 3자 이상 적어 주세요.": ["Use at least 3 Latin or Korean letters.", "英字かハングルで3文字以上入力してください。", "请用拉丁字母或韩文输入至少 3 个字。"],
  "원래 이름은 이미 누가 쓰고 있어서 {0}(으)로 만들어요.": ["That name is already taken, so this will use {0}.", "その名前はすでに使われているため、{0} で作ります。", "该名称已被使用，将改用 {0} 创建。"],
  "이 RVN은 네트워크에 태워져 이름과 기록을 지키는 데 쓰여요. 저희가 받는 돈이 아니에요.": ["This RVN is burned by the network to secure the name and record. It is not paid to us.", "このRVNはネットワークで焼却され、名前と記録を守るために使われます。私たちが受け取るお金ではありません。", "这些 RVN 会被网络销毁，用来保护名称和记录，不是付给我们的钱。"],
  "이 이름은 이미 다른 사람들이 쓰고 있어요. 다른 이름을 적어 주세요.": ["This name is already used by others. Enter a different name.", "この名前はすでにほかの人が使っています。別の名前を入力してください。", "该名称已被他人使用，请换一个名称。"],
  "이렇게 만들어요": ["Here is what will be created", "このように作ります", "将这样创建"],
  "이름 등록이 끝났어요": ["Your name is registered", "名前の登録が終わりました", "名称已注册"],
  "이름 등록하고 만들기": ["Register name and create", "名前を登録して作る", "注册名称并创建"],
  "이름을 등록하는 중이에요": ["Registering your name", "名前を登録しています", "正在注册名称"],
  "작품": ["Artwork", "作品", "作品"],
  "작품 만들기": ["Create an artwork", "作品を作る", "创建作品"],
  "증명서": ["Certificate", "証明書", "证书"],
  "증명서 · 티켓 · 작품": ["Certificates · Tickets · Artworks", "証明書 · チケット · 作品", "证书 · 门票 · 作品"],
  "증명서 만들기": ["Create a certificate", "証明書を作る", "创建证书"],
  "증명서 확인 링크 — 받는 사람에게 이 QR이나 링크를 보내 주세요.": ["Certificate check link — send this QR or link to the recipient.", "証明書の確認リンク — 受け取る人にこのQRかリンクを送ってください。", "证书查验链接 — 请把这个二维码或链接发给接收人。"],
  "증명서·티켓·작품을 만듭니다. 고르고, 제목과 장수만 적으면 됩니다.": ["Create certificates, tickets and artworks. Pick one, then just enter a title and how many.", "証明書・チケット・作品を作ります。選んで、タイトルと枚数を書くだけです。", "创建证书、门票和作品。选一个，只需填写标题和数量。"],
  "처음 한 번은 이름 {0} 등록(500 RVN)이 들어가요. 다음부터는 만드는 값만 들어요.": ["The first time includes registering the name {0} (500 RVN). After that, you only pay to create.", "初回だけ名前 {0} の登録（500 RVN）がかかります。次からは作る分だけです。", "第一次需要注册名称 {0}（500 RVN），之后只需支付创建费用。"],
  "처음부터 다시": ["Start over", "最初からやり直す", "重新开始"],
  "체인에 새겨질 이름": ["Name written on the chain", "チェーンに刻まれる名前", "写入链上的名称"],
  "체인에는 {0}(으)로 새겨요": ["It will be written on the chain as {0}", "チェーンには {0} と刻みます", "链上将写作 {0}"],
  "티켓": ["Ticket", "チケット", "门票"],
  "티켓 {0}장 · 나중에 더 만들 수 있어요": ["{0} tickets · You can make more later", "チケット{0}枚 · あとで追加できます", "{0} 张门票 · 之后还能增发"],
  "티켓 만들기": ["Create tickets", "チケットを作る", "创建门票"],
  "티켓 몇 장": ["How many tickets", "チケット何枚", "门票几张"],
  "파일 없이 만들어요.": ["No file attached.", "ファイルなしで作ります。", "不附加文件。"],
  "파일 지문을 만드는 중…": ["Fingerprinting the file…", "ファイルの指紋を作っています…", "正在生成文件指纹…"],
  "파일 지문을 만들지 못했어요: {0}": ["Could not fingerprint the file: {0}", "ファイルの指紋を作れませんでした: {0}", "无法生成文件指纹：{0}"],
  "파일 지문을 함께 새겨요 · {0}": ["The file fingerprint is included · {0}", "ファイルの指紋も刻みます · {0}", "同时写入文件指纹 · {0}"],
  "파일은 올리지 않아요. 이 컴퓨터에서 지문만 만들어 체인에 새겨요.": ["The file is not uploaded. This computer only makes its fingerprint and writes that on the chain.", "ファイルはアップロードしません。このコンピューターで指紋だけを作ってチェーンに刻みます。", "文件不会上传。这台电脑只生成指纹并写入链上。"],
  "필요한 RVN": ["RVN needed", "必要なRVN", "所需 RVN"],
  "하나 더 만들기": ["Create another", "もう一つ作る", "再创建一个"],
  "확인 페이지 열기": ["Open the check page", "確認ページを開く", "打开查验页面"],
  "확인하기": ["Check", "確認する", "检查"],
  "방금 만든 것이 기록되는 중이에요. 1~2분 뒤에 다시 확인해 주세요.": ["What you just created is still being recorded. Check again in 1–2 minutes.", "作ったばかりのものを記録しています。1〜2分後にもう一度確認してください。", "刚创建的内容正在记录中，请 1–2 分钟后再检查。"],
  "이 등록은 무효가 됐어요. 「처음부터 다시」를 눌러 주세요.": ["This registration became invalid. Press Start over.", "この登録は無効になりました。「最初からやり直す」を押してください。", "这次注册已失效，请点“重新开始”。"],
};
