/** Korean source copy + English, Japanese and Simplified Chinese. User text is not translated here. */
export const DESKTOP_COPY: Record<string, [string, string, string]> = {
  "확인 대기 중": ["Pending confirmation", "承認待ち", "等待确认"],
  "이 자산에는 아직 프로필이 안 붙어 있습니다.": ["This asset has no profile yet.", "この資産にはまだプロフィールがありません。", "此资产尚无个人资料。"],
  "체인 프로필에 열쇠가 안 적혀 있습니다.": ["The on-chain profile has no key.", "チェーン上のプロフィールにキーがありません。", "链上个人资料中没有密钥。"],
  "체인이 가리키는 열쇠와 이 컴퓨터의 열쇠가 다릅니다. 12단어가 같은지 확인해 주세요.": ["The on-chain key differs from this computer’s key. Check that the recovery words match.", "チェーン上のキーとこのコンピュータのキーが異なります。復元単語が同じか確認してください。", "链上密钥与此电脑的密钥不同。请检查助记词是否一致。"],
  "메시지": ["Message", "メッセージ", "消息"],
  "표시할 이름": ["Display name", "表示名", "显示名称"],
  "한두 줄이면 됩니다": ["One or two lines is enough", "1〜2行で十分です", "一两行即可"],
  "암호 (10글자 이상)": ["Password (at least 10 characters)", "パスワード（10文字以上）", "密码（至少10个字符）"],
  "최신 버전": ["Up to date", "最新版", "已是最新版"],
  "RVN 노드 꺼짐": ["RVN node off", "RVN ノード停止中", "RVN 节点已关闭"],
  "RVN 노드 여는 중": ["Starting RVN node", "RVN ノード起動中", "RVN 节点启动中"],
  "예: 내 이름": ["e.g. My name", "例：自分の名前", "例如：我的名称"],
  "설정": ["Settings", "設定", "设置"],
  "켜짐": ["On", "稼働中", "已开启"],
  "동기화": ["Syncing", "同期中", "同步中"],
  "아직 이름이 없습니다": ["No name yet", "名前はまだありません", "尚未设置名称"],
  "아직 이름이 없습니다. 얼굴과 이름을 여기 올리면 됩니다 — 공짜입니다.": ["No name yet. Add your name and photo here for free.", "名前はまだありません。ここで名前と写真を無料で公開できます。", "尚未设置名称。您可以在这里免费添加名称和照片。"],
  "한눈에": ["At a glance", "ひと目で確認", "一览"],
  "내 노드": ["My node", "自分のノード", "我的节点"],
  "확정 잔액": ["Confirmed balance", "確定残高", "已确认余额"],
  "설정으로": ["Open settings", "設定を開く", "打开设置"],
  "설정 · 언어": ["Settings · Language", "設定 · 言語", "设置 · 语言"],
  "언어는 바로 바뀌며 다음 실행에도 기억합니다.": ["Language changes immediately and is saved for next time.", "言語はすぐに切り替わり、次回も保持されます。", "语言会立即切换，并在下次启动时保留。"],
  "Mac에서 기존 앱의 파일 이름은 그대로 남을 수 있습니다. 앱 안의 이름은 RavenVault Desktop입니다.": ["On Mac, the existing app file may keep its old name. Inside the app, the name is RavenVault Desktop.", "Macでは既存のアプリファイル名が残る場合があります。アプリ内の名前は RavenVault Desktop です。", "在 Mac 上，现有应用文件可能保留旧名称。应用内的名称为 RavenVault Desktop。"],
  "이야기": ["Chat", "トーク", "聊天"],
  "RVN 노드 켜짐": ["RVN node on", "RVN ノード稼働中", "RVN 节点已开启"],
  "채굴 꺼짐": ["Mining off", "採掘停止中", "挖矿已关闭"],
  "릴레이 꺼짐": ["Relay off", "リレー停止中", "中继已关闭"],
  "못 읽음": ["Could not read", "読み取れません", "无法读取"],
  "바깥 연결이 꺼져 있습니다 →": ["External connection is off →", "外部接続は停止中です →", "外部连接已关闭 →"],
  "바깥 연결이 꺼져 있습니다": ["External connection is off", "外部接続は停止中です", "外部连接已关闭"],
  "방": ["Rooms", "ルーム", "房间"],
  "레이븐 이야기": ["Ravencoin chat", "Ravencoin トーク", "Ravencoin 聊天"],
  "+ 방 만들기": ["+ Create room", "+ ルームを作成", "+ 创建房间"],
  "초대하기": ["Invite", "招待", "邀请"],
  "더 보기": ["More", "もっと見る", "更多"],
  "이름은 누구나 같게 달 수 있습니다.": ["Anyone can use the same name.", "同じ名前は誰でも使えます。", "任何人都可以使用相同的名称。"],
  "돈이나 주소 이야기는 이름만 보고 믿지 마세요. 글은 세계 릴레이로 나갑니다.": ["Do not trust payment or address claims based on a name alone. Posts go to public relays.", "送金やアドレスの話を名前だけで信用しないでください。投稿は公開リレーに送られます。", "请勿仅凭名称相信有关付款或地址的信息。消息会发送到公共中继。"],
  "글을": ["A post:", "投稿を", "消息："],
  "누르면": ["click it", "押すと", "点击后"],
  "「내 말로」·「간직」·「안 보기」 단추가 나옵니다. 사진은 아래": ["to translate, save or hide it. Add images with", "翻訳・保存・非表示ボタンが出ます。画像は下の", "可翻译、保存或隐藏。图片可通过下方的"],
  "「사진」": ["“Photo”", "「写真」", "“照片”"],
  "단추로 고르거나, 창에": ["or into the window,", "ボタンで選ぶか、ウィンドウに", "按钮选择，或向窗口"],
  "끌어다 놓으면": ["drag and drop", "ドラッグ＆ドロップ", "拖放"],
  "됩니다.": ["to attach.", "してください。", "即可添加。"],
  "사진": ["Photo", "写真", "照片"],
  "거래 내역이 없습니다": ["No transactions yet", "取引履歴はありません", "暂无交易记录"],
  "파일창고(IPFS)": ["File storage (IPFS)", "ファイル保管庫 (IPFS)", "文件存储 (IPFS)"],
  "가진 사람들에게": ["To holders", "保有者へ", "发送给持有者"],
  "팬클럽": ["Fan club", "ファンクラブ", "粉丝俱乐部"],
  "음반마다 팬 방 · 한 번에 알리기": ["Fan rooms by release · notify together", "作品ごとのファンルーム・まとめて通知", "每张专辑的粉丝房间 · 一次通知"],
  "맞교환": ["Swap", "交換", "交换"],
  "— 모르는 사람과도 안전하게 사고팔기": ["— Trade safely with new people", "— 初めての相手とも安全に取引", "— 与陌生人安全交易"],
  "— 음반·그림마다 팬 방 · 여러 방에 한 번에 알리기": ["— Fan rooms for music and art · notify multiple rooms", "— 音楽・絵ごとのファンルーム・複数ルームに一括通知", "— 音乐和画作的粉丝房间 · 一次通知多个房间"],
  "전체 0": ["All 0", "すべて 0", "全部 0"],
  "내가 만든 것 0": ["Created 0", "作成したもの 0", "我创建的 0"],
  "받은 것 0": ["Received 0", "受け取ったもの 0", "收到的 0"],
  "판매중 0": ["For sale 0", "販売中 0", "出售中 0"],
  "자산 0개 · 파일 있음 0개 · 보존 중 0개": ["Assets 0 · With files 0 · Preserved 0", "資産 0 · ファイルあり 0 · 保管中 0", "资产 0 · 含文件 0 · 保存中 0"],
  "웹에서 산 사람에게 보낼 것": ["Deliveries for web buyers", "ウェブ購入者への配送", "发送给网页买家的内容"],
  "열쇠 바꾸기": ["Change key", "キーを変更", "更换密钥"],
  "웹 주문 가져오기": ["Import web orders", "ウェブ注文を取り込む", "导入网页订单"],
  "웹(rvn.ex.erci.se)에서 산 사람에게 보내려면 배송 열쇠가 필요합니다. 아래 「웹 주문 가져오기」를 누르세요.": ["A delivery key is needed for web buyers (rvn.ex.erci.se). Click “Import web orders” below.", "ウェブ (rvn.ex.erci.se) の購入者への配送には専用キーが必要です。下の「ウェブ注文を取り込む」を押してください。", "向网页 (rvn.ex.erci.se) 买家发货需要配送密钥。请点击下方的“导入网页订单”。"],
  "받을 주소": ["Receiving address", "受取アドレス", "收款地址"],
  "해당하는 자산이 없습니다.": ["No matching assets.", "該当する資産はありません。", "没有匹配的资产。"],
  "손님이 보는 얼굴입니다. 「이야기」의 내 이름과": ["This is your public profile. It is", "お客様に見えるプロフィールです。「トーク」の名前とは", "这是顾客看到的个人资料，与“聊天”中的名称"],
  "다른 자리": ["separate", "別のもの", "分开"],
  "입니다 — 개인 대화와 섞이지 않습니다.": ["from your chat name and private conversations.", "で、個人の会話とは混ざりません。", "，不会与私人对话混在一起。"],
  "X·인스타·유튜브 중": ["From X, Instagram or YouTube, add", "X・Instagram・YouTube のうち", "从 X、Instagram 或 YouTube 中"],
  "하나": ["one link", "1つ", "选择一个"],
  "만 적습니다. 칸이 많으면 안 적게 됩니다.": ["to keep it simple.", "だけを記入してください。", "链接即可。"],
  "SHOP.PLAYX 수량을 못 읽었습니다. 노드가 켜져 있는지 보세요.": ["Could not read the SHOP.PLAYX amount. Check that the node is on.", "SHOP.PLAYX の数量を読み取れません。ノードの起動を確認してください。", "无法读取 SHOP.PLAYX 数量。请确认节点已开启。"],
  "손님을 받으시려면": ["To welcome customers", "お客様を迎えるには", "如需接待顾客"],
  "손님 QR · 테이블": ["Customer QR · Tables", "お客様用 QR · テーブル", "顾客二维码 · 桌号"],
  "한 번에 준비하기": ["Set up together", "まとめて準備", "一键准备"],
  "백신 · 방화벽 · 메모리": ["Antivirus · Firewall · Memory", "ウイルス対策 · ファイアウォール · メモリ", "杀毒软件 · 防火墙 · 内存"],
  "백업": ["Backup", "バックアップ", "备份"],
  "새 주문 소리": ["New order sound", "新規注文の音", "新订单提示音"],
  "손님 주문이 들어오거나": ["When an order arrives or", "注文が入ったときや", "收到顾客订单或"],
  "입금이 확인되면": ["a payment is confirmed,", "入金が確認されたときに", "确认收款时，"],
  "소리로 알려 드립니다. 창을 안 보고 계실 때는 한 번 더 울립니다.": ["a sound plays. It repeats once if the window is not focused.", "音でお知らせします。ウィンドウを見ていないときはもう一度鳴ります。", "会播放提示音。窗口未聚焦时会再响一次。"],
  "주문·입금이 들어오면 소리로 알리기": ["Play sounds for orders and payments", "注文・入金を音で通知", "订单和收款声音通知"],
  "소리 들어보기": ["Preview sound", "音を試す", "试听提示音"],
  "밤새 켜 두는 컴퓨터라면 꺼 두세요. 꺼도": ["Turn off on an overnight computer. Even with sounds off,", "夜通し使うコンピュータではオフにしてください。オフでも", "电脑整夜运行时可关闭。即使关闭，"],
  "주문은 그대로 들어옵니다": ["orders still arrive", "注文は引き続き届きます", "仍会收到订单"],
  "— 소리와 빨간 숫자만 안 나옵니다.": ["— only sound and the red count are disabled.", "— 音と赤い件数表示だけがなくなります。", "— 仅停用声音和红色数字提醒。"],
  "대화 알림 소리": ["Chat notification sound", "トークの通知音", "聊天提示音"],
  "「이야기」 방에 새 글이 오면": ["When a new chat message arrives,", "「トーク」に新しい投稿が届くと", "“聊天”房间收到新消息时，"],
  "낮은 소리로 한 번": ["a soft sound", "小さな音で一度", "轻声响一次"],
  "알려 드립니다. 주문 소리(딩—동)와 일부러 다르게 했습니다 — 돈과 말은 급한 정도가 다릅니다.": ["plays, distinct from the order chime so you can tell them apart.", "お知らせします。注文の音とは区別できます。", "，与订单提示音不同，方便区分。"],
  "내가 쓴 글": ["Your own posts", "自分の投稿", "自己发送的消息"],
  "에는 울리지 않습니다.": ["do not trigger sounds.", "では鳴りません。", "不会触发提示音。"],
  "지금 보고 있는 방": ["The room you are viewing", "表示中のルーム", "正在查看的房间"],
  "에도 울리지 않습니다 — 눈앞에 글이 뜨는 것이 이미 답입니다.": ["also stays silent because you can already see the message.", "でも鳴りません。投稿が画面に表示されるためです。", "也不会响铃，因为消息已显示在眼前。"],
  "이야기에 새 글이 오면 소리로 알리기": ["Play a sound for new chat messages", "トークの新着を音で通知", "聊天新消息声音通知"],
  "위 「새 주문 소리」와": ["From the order sound above, this is", "上の「新規注文の音」とは", "与上方的“新订单提示音”"],
  "따로 켜고 끕니다.": ["controlled separately.", "別々に切り替えます。", "分别控制。"],
  "이것만 꺼도 주문 소리는 그대로 납니다. 꺼도": ["Turning this off keeps order sounds on.", "これをオフにしても注文の音は鳴ります。", "仅关闭此项不会影响订单提示音。"],
  "새 글은 그대로 들어옵니다": ["New messages still arrive", "新しい投稿は引き続き届きます", "仍会收到新消息"],
  "— 소리와 왼쪽 「이야기」 옆 숫자만 안 나옵니다.": ["— only sounds and the sidebar chat count are disabled.", "— 音と左の「トーク」横の件数だけがなくなります。", "— 仅停用声音和左侧“聊天”旁的数字。"],
  "레이븐 코어 지갑": ["Ravencoin Core wallet", "Ravencoin Core ウォレット", "Ravencoin Core 钱包"],
  "폴더": ["Folder", "フォルダー", "文件夹"],
  "기존 지갑 폴더 고르기": ["Choose existing wallet folder", "既存のウォレットフォルダーを選ぶ", "选择现有钱包文件夹"],
  "레이븐 코어를 쓰던 컴퓨터면": ["If this computer used Ravencoin Core,", "Ravencoin Core を使っていた場合、", "如果此电脑使用过 Ravencoin Core，"],
  "그 wallet.dat 폴더": ["the same wallet.dat folder", "同じ wallet.dat フォルダー", "同一个 wallet.dat 文件夹"],
  "를 그대로 씁니다. 코어와 이 프로그램은 같은 지갑이라": ["is reused. Core and this app share a wallet and", "を使います。Core とこのアプリは同じウォレットなので", "会被继续使用。Core 与此应用共用钱包，因此"],
  "동시에 열 수 없습니다.": ["cannot run at the same time.", "同時には開けません。", "不能同时打开。"],
  "내 이름": ["My identity", "自分の ID", "我的身份"],
  "이 컴퓨터의 「나」와 폰·웹 지갑의 「나」가": ["Check whether your computer and phone or web wallet", "このコンピュータとスマートフォン・ウェブのウォレットが", "检查此电脑与手机或网页钱包"],
  "같은 사람인지": ["share the same identity", "同じ ID か", "是否为同一身份"],
  "봅니다. 「이야기」에 적는 별명이 아니라, 그 별명을 붙이는": ["using the underlying", "を確認します。「トーク」のニックネームではなく、その", "，依据是背后的"],
  "열쇠": ["key", "キー", "密钥"],
  "이야기입니다 — 별명은 누구나 같게 달 수 있어서 그것으로는 같은 사람인지 알 수 없습니다.": ["rather than a nickname, which anyone can copy.", "で判断します。同じニックネームは誰でも使えるためです。", "，而非任何人都能使用的昵称。"],
  "같은 사람인지 확인할 수 없습니다.": ["Could not verify a shared identity.", "同じ ID か確認できません。", "无法确认是否为同一身份。"],
  "무작위로 만들어졌습니다 — 12단어로는 되살릴 수 없습니다": ["Randomly generated — cannot be restored with 12 words", "ランダムに生成されました — 12単語では復元できません", "随机生成 — 无法通过12个助记词恢复"],
  "폰 · 웹 지갑": ["Phone · Web wallet", "スマートフォン · ウェブウォレット", "手机 · 网页钱包"],
  "12단어에서 나오는 이름": ["Identity derived from 12 words", "12単語から生成される ID", "由12个助记词生成的身份"],
  "12단어를 읽지 못했습니다.": ["Could not read the recovery words.", "復元単語を読み取れませんでした。", "无法读取助记词。"],
  "지갑이 잠겨 있으면 열어 주세요. 12단어로 만든 지갑이 아니면, 이 이름은 백업 파일이 유일한 사본입니다 — 파일을 잃으면 이 이름으로 다시 못 돌아옵니다.": ["Unlock the wallet if locked. If it was not created from 12 words, only the backup preserves this identity. Losing that file loses the identity.", "ロック中ならウォレットを解除してください。12単語で作成していない場合、この ID はバックアップからのみ復元できます。ファイルを失うと ID も失います。", "钱包若已锁定，请先解锁。如果并非由12个助记词创建，此身份只能从备份恢复。丢失备份就会丢失此身份。"],
  "가게 간판 열쇠": ["Shop identity key", "お店の看板キー", "店铺身份密钥"],
  "아직 가게 간판 열쇠가 없습니다.": ["No shop identity key yet.", "お店の看板キーはまだありません。", "尚无店铺身份密钥。"],
  "무엇이 12단어 어디에서 나오나": ["How the 12 words derive each key", "12単語からのキー生成元", "各密钥如何从12个助记词派生"],
  "돈 · 사람 · 가게 간판 — 어느 자리에서 뽑는지 적어 둔 표": ["Derivation paths for funds, identity and shop keys", "資金・個人 ID・お店のキーの派生パス", "资金、个人身份和店铺密钥的派生路径"],
  "가게 결제 · 벤딩머신 · 자산 맞교환 · 중고 물건 사기": ["Shop payments · Vending · Asset swaps · Used goods", "お店の決済 · 自販機 · 資産交換 · 中古品の購入", "店铺付款 · 自动售货 · 资产交换 · 二手物品购买"],
  "끄는 설정은 없습니다.": ["There is no off switch.", "無効にする設定はありません。", "没有关闭选项。"],
  "대신 체인에서 직접 대조하실 수 있고, 소스가 전부 공개돼 있습니다. 카드 수수료(2~3%)와 달리": ["You can verify it on chain and inspect the open source. Unlike card fees (2–3%),", "チェーンで照合でき、ソースも公開されています。カード手数料 (2〜3%) と違い、", "您可以在链上核对，源代码也完全公开。与银行卡手续费 (2–3%) 不同，"],
  "단말기 임대료도 정산 대기도 해지 위약금도 없습니다.": ["there is no terminal rental, settlement wait or cancellation penalty.", "端末のレンタル料、入金待ち、解約違約金はありません。", "没有终端租赁费、结算等待或解约罚款。"],
  "기본값": ["Default", "既定値", "默认值"],
  "살펴본 것 — 일꾼 모름 · 기억장치 모름 · 빈 공간 모름": ["Hardware — CPU unknown · Memory unknown · Free space unknown", "ハードウェア — CPU 不明 · メモリ不明 · 空き容量不明", "硬件 — CPU 未知 · 内存未知 · 可用空间未知"],
  "지금 받을 수 있는지 못 알아봤습니다": ["Could not check readiness to receive", "受取可能か確認できませんでした", "无法确认当前是否可收款"],
  "노드가 켜져 있는지 보고, 잠시 뒤 이 화면을 다시 열어 주세요.": ["Check that the node is on, then reopen this screen shortly.", "ノードの起動を確認し、しばらくしてからこの画面を開き直してください。", "请确认节点已开启，稍后重新打开此页面。"],
  "가게를 다른 컴퓨터로 옮기기": ["Move shop to another computer", "お店を別のコンピュータへ移す", "将店铺迁移至其他电脑"],
  "전부 보내기": ["Transfer all", "すべて移す", "迁移全部"],
  "가게만 보내기": ["Transfer shop only", "お店だけ移す", "仅迁移店铺"],
  "가져오기": ["Import", "取り込む", "导入"],
  "전부": ["All", "すべて", "全部"],
  "— 이 컴퓨터를 그만 쓰실 때. 지갑까지 갑니다": ["— For retiring this computer. Includes the wallet", "— このコンピュータを使わなくなるとき。ウォレットも含みます", "— 停用此电脑时使用，包含钱包"],
  "가게만": ["Shop only", "お店だけ", "仅店铺"],
  "— 돈은 이 컴퓨터에 남습니다. 새 컴퓨터는 카운터가 됩니다": ["— Funds stay here. The new computer becomes the counter", "— 資金はここに残ります。新しいコンピュータがカウンターになります", "— 资金留在此电脑，新电脑用作收银台"],
  "꺼져 있습니다.": ["It is off.", "停止しています。", "已关闭。"],
  "번 돈이 계속 이 컴퓨터에 쌓입니다.": ["Earnings keep arriving on this computer.", "売上は引き続きこのコンピュータに届きます。", "收入仍会留在此电脑。"],
  "아직 암호를 안 정하셨습니다.": ["No password set yet.", "パスワードはまだ設定されていません。", "尚未设置密码。"],
  "컴퓨터가 죽으면 이 열쇠도 같이 사라져서 백업을 못 엽니다.": ["If this computer fails, the key may be lost and the backup cannot be opened.", "コンピュータが故障するとキーも失われ、バックアップを開けなくなる場合があります。", "电脑损坏时，密钥可能丢失，导致无法打开备份。"],
  "아래에서 암호를 정하시거나": ["Set a password below, or", "下でパスワードを設定するか", "请在下方设置密码，或"],
  ", 이 열쇠를 종이에 적어 12단어와 같이 보관하세요.": ["write this key on paper and keep it with your recovery words.", "このキーを紙に書き、復元単語と一緒に保管してください。", "将此密钥写在纸上，与助记词一同保管。"],
  "외우는 암호로도 열기": ["Also unlock with a password", "パスワードでも開く", "也可使用密码打开"],
  "「지갑」 화면에서 암호를 거시면 이것도 같이 정해집니다.": ["Setting a password on the Wallet screen also sets this.", "「ウォレット」でパスワードを設定すると、こちらにも設定されます。", "在“钱包”页面设置密码时，此处也会同步设置。"],
  "따로 정하실 필요가 없습니다. 아래는 지갑 암호를 아직 안 걸었거나,": ["No separate setup is needed. Use this if the wallet has no password, or for", "別途設定は不要です。ウォレットにパスワードがない場合や、", "无需单独设置。钱包尚未设置密码，或需要"],
  "백업만 다른 암호로": ["a separate backup password", "バックアップ専用のパスワード", "为备份使用不同密码"],
  "두고 싶을 때 씁니다.": ["when needed.", "を使う場合に設定してください。", "时，可在此设置。"],
  "돈을 보낼 때 — 「지갑」 화면": ["When sending funds — Wallet screen", "送金するとき —「ウォレット」画面", "发送资金时 —“钱包”页面"],
  "이 암호": ["This password", "このパスワード", "此密码"],
  "새 컴퓨터에서 백업을 열 때": ["When opening the backup on a new computer", "新しいコンピュータでバックアップを開くとき", "在新电脑上打开备份时"],
  "이 암호로 정하기": ["Set this password", "このパスワードを設定", "设置此密码"],

  "없음": ["None", "なし", "无"],
  "메인넷 노드의 연결과 동기화 상태를 확인하세요.": ["Check the mainnet node connection and sync status.", "メインネットのノードの接続と同期状態を確認してください。", "请检查主网节点的连接和同步状态。"],
  "내 노드로 조회하고, 폰에서 서명한 거래를 보냅니다.": ["Look up the chain through your node and send transactions signed on your phone.", "自分のノードで照会し、スマートフォンで署名した取引を送信します。", "通过自己的节点查询，并发送手机上已签名的交易。"],
  "분할 QR은 모든 조각을 한 줄에 하나씩 붙여넣으세요.": ["For a split QR, paste every part on its own line.", "分割 QR は、全ての断片を1行ずつ貼り付けてください。", "对于分段二维码，请每行粘贴一个片段，包含全部片段。"],
  "거래 조각이 부족합니다. 모든 조각을 한 줄에 하나씩 붙여넣으세요.": ["Transaction parts are missing. Paste every part on its own line.", "取引の断片が足りません。全ての断片を1行ずつ貼り付けてください。", "交易片段不完整。请每行粘贴一个片段，包含全部片段。"],
  "폰에서 RavenVault 쓰기": ["Use RavenVault on your phone", "スマートフォンで RavenVault を使う", "在手机上使用 RavenVault"],
  "폰에서 서명한 거래 보내기": ["Send a transaction signed on your phone", "スマートフォンで署名した取引を送信", "发送手机已签名的交易"],
  "열쇠는 폰에, 전파는 내 노드로": ["Keys on your phone, relay through your node", "鍵はスマートフォンに、送信は自分のノードから", "密钥留在手机，通过自己的节点广播"],
  "물어보고 시키는 곳. AI는 직접 켤 때만 사용합니다.": ["Ask questions and give instructions. AI runs only when you enable it.", "質問や指示をする場所です。AI は自分で有効にした場合のみ使います。", "在这里提问和发出指令。AI 仅在您主动启用时使用。"],
  "열쇠는 폰에 남습니다. 이 컴퓨터는 내용을 확인하고 내 노드로 전파합니다.": ["Keys stay on your phone. This computer reviews the transaction and relays it through your node.", "鍵はスマートフォンに残ります。このコンピュータで内容を確認し、自分のノードから送信します。", "密钥留在手机上。此电脑检查交易内容，并通过您的节点广播。"],
  "폰의 서명 거래 코드 붙여넣기": ["Paste the signed transaction code from your phone", "スマートフォンの署名済み取引コードを貼り付け", "粘贴手机上的已签名交易代码"],
  "보내기 전 내용 확인": ["Review before sending", "送信前に内容を確認", "发送前检查内容"],
  "입력 지우기": ["Clear input", "入力を消去", "清除输入"],
  "확인하고 네트워크에 보내기": ["Confirm and send to the network", "確認してネットワークに送信", "确认并发送到网络"],
  "폰 카메라로 찍으면 RavenVault가 열립니다. 폰 지갑과 이 컴퓨터의 지갑은 별개이며 잔액이 자동으로 합쳐지지 않습니다.": ["Scan with your phone camera to open RavenVault. The phone and computer wallets are separate; balances do not merge automatically.", "スマートフォンのカメラで読み取ると RavenVault が開きます。スマートフォンとコンピュータのウォレットは別々で、残高は自動で統合されません。", "用手机摄像头扫描即可打开 RavenVault。手机钱包和电脑钱包彼此独立，余额不会自动合并。"],
  "브라우저로 열기": ["Open in browser", "ブラウザで開く", "在浏览器中打开"],
  "같은 컴퓨터의 Chrome에서 http://127.0.0.1:8790에 연결할 때는 로컬 네트워크 접근을 허용해야 합니다. 노드와 손님 서버가 켜져 있어야 합니다.": ["In Chrome on this computer, connecting to http://127.0.0.1:8790 requires Local Network Access permission. The node and customer server must be running.", "このコンピュータの Chrome で http://127.0.0.1:8790 に接続するには、ローカルネットワークへのアクセスを許可してください。ノードとお客様用サーバーの起動が必要です。", "在此电脑的 Chrome 中连接 http://127.0.0.1:8790 时，需要允许本地网络访问。节点和顾客服务器必须正在运行。"],
  "다른 기기에서는 127.0.0.1로 이 컴퓨터에 연결할 수 없습니다. 폰에서는 접근 가능한 이 컴퓨터의 노드 주소를 설정하세요.": ["Other devices cannot reach this computer at 127.0.0.1. On your phone, configure a reachable node address for this computer.", "他の端末から 127.0.0.1 でこのコンピュータには接続できません。スマートフォンには、このコンピュータに接続可能なノードのアドレスを設定してください。", "其他设备无法通过 127.0.0.1 连接此电脑。请在手机上设置可访问的此电脑节点地址。"],
  "브라우저에 RavenVault를 열었습니다.": ["Opened RavenVault in your browser.", "ブラウザで RavenVault を開きました。", "已在浏览器中打开 RavenVault。"],
  "QR을 만들지 못했습니다. 아래 주소를 폰에서 열어 주세요.": ["Could not create the QR code. Open the address below on your phone.", "QR コードを作成できませんでした。下のアドレスをスマートフォンで開いてください。", "无法生成二维码。请在手机上打开下方地址。"],
  "거래 코드의 형식·버전·길이를 확인하세요. 폰에서 서명한 거래 코드를 다시 복사하세요.": ["Check the transaction code format, version and length. Copy the signed transaction code from your phone again.", "取引コードの形式・バージョン・長さを確認し、スマートフォンの署名済みコードをコピーし直してください。", "请检查交易代码的格式、版本和长度，并重新复制手机上的已签名交易代码。"],
  "거래 내용을 확인하는 중입니다. 아직 보내지 않았습니다.": ["Reviewing the transaction. It has not been sent.", "取引内容を確認中です。まだ送信していません。", "正在检查交易内容，尚未发送。"],
  "거래 ID": ["Transaction ID", "取引 ID", "交易 ID"],
  "출력 안내": ["About outputs", "出力について", "输出说明"],
  "거스름돈을 포함한 모든 출력입니다. 받는 사람과 거스름돈은 자동으로 구분하지 못합니다.": ["All outputs are shown, including change. Recipient and change outputs cannot be distinguished automatically.", "お釣りを含む全出力です。受取先とお釣りは自動では区別できません。", "这里显示包含找零的全部输出，无法自动区分收款和找零。"],
  "출력": ["Output", "出力", "输出"],
  "받는 주소": ["Recipient address", "受取先アドレス", "收款地址"],
  "RVN 금액": ["RVN amount", "RVN 金額", "RVN 金额"],
  "자산": ["Asset", "資産", "资产"],
  "수수료": ["Fee", "手数料", "手续费"],
  "확인 못 함": ["Unable to verify", "確認できません", "无法确认"],
  "아직 보내지 않았습니다. 폰의 내용과 대조한 뒤 확인하고 보내세요.": ["Not sent yet. Compare with your phone, then confirm and send.", "まだ送信していません。スマートフォンの内容と照合し、確認して送信してください。", "尚未发送。请与手机上的内容核对，然后确认发送。"],
  "네트워크에 보내는 중입니다.": ["Sending to the network.", "ネットワークに送信中です。", "正在发送到网络。"],
  "노드가 거래를 받았습니다. 블록 확정은 아직 확인 못 함.": ["The node accepted the transaction. Block confirmation has not yet been verified.", "ノードが取引を受け付けました。ブロックでの確定はまだ確認できません。", "节点已接受交易，尚未确认是否已在区块中确认。"],
  "전파 결과를 확인 못 했습니다. 다시 보내기 전에 거래 ID로 확인하세요.": ["Could not verify the relay result. Check the transaction ID before sending again.", "送信結果を確認できませんでした。再送信の前に取引 ID で確認してください。", "无法确认广播结果。再次发送前，请通过交易 ID 查询。"],
  "노드에 연결하지 못했습니다. 이 컴퓨터에서 노드 상태를 확인하세요.": ["Could not connect to the node. Check its status on this computer.", "ノードに接続できませんでした。このコンピュータで状態を確認してください。", "无法连接节点。请在此电脑上检查节点状态。"],
  "메인넷 노드와 메인넷 받는 주소만 사용할 수 있습니다.": ["Only a mainnet node and mainnet recipient addresses are supported.", "メインネットのノードと受取先アドレスのみ使用できます。", "仅支持主网节点和主网收款地址。"],
  "노드가 동기화 중입니다. 완료한 뒤 다시 확인하세요.": ["The node is syncing. Review again once it finishes.", "ノードは同期中です。完了後に再度確認してください。", "节点正在同步，请完成后重试。"],
  "이미 네트워크에 알려진 거래입니다. 거래 ID로 확인하세요.": ["This transaction is already known to the network. Check its transaction ID.", "ネットワークで既知の取引です。取引 ID で確認してください。", "网络已知此交易。请通过交易 ID 查询。"],
  "입력을 찾을 수 없습니다. 이미 사용했거나 아직 노드가 확인하지 못한 입력입니다.": ["Inputs are unavailable. They may be spent or not yet known to the node.", "入力が見つかりません。使用済み、またはノードがまだ確認できていない可能性があります。", "找不到输入，可能已花费或节点尚未确认。"],
  "노드가 거래를 거부했습니다. 서명·잔액·수수료를 폰에서 다시 확인하세요.": ["The node rejected the transaction. Recheck the signature, balance and fee on your phone.", "ノードが取引を拒否しました。スマートフォンで署名・残高・手数料を再確認してください。", "节点拒绝了交易。请在手机上重新检查签名、余额和手续费。"],
  "거래 내용을 확인한 뒤 보내기 단추를 눌러 주세요.": ["Review the transaction, then press Send.", "取引内容を確認してから送信ボタンを押してください。", "请确认交易内容后再按发送按钮。"],

  "폴더에서 되돌리기": ["Restore from folder", "フォルダーから復元", "从文件夹恢复"],
  "되돌릴 백업 폴더를 고르세요": ["Choose a backup folder to restore", "復元するバックアップフォルダーを選んでください", "请选择要恢复的备份文件夹"],

  "되돌리기를 완료했습니다": ["Restore completed", "復元が完了しました", "恢复已完成"],
  "일부만 되돌렸습니다": ["Only some items were restored", "一部の項目のみ復元しました", "仅恢复了部分项目"],
  "되돌리기를 완료하지 못했습니다": ["Restore did not complete", "復元を完了できませんでした", "未能完成恢复"],
  "보존한 이전 파일을 확인하기 전에는 지우지 마세요.": ["Do not delete the preserved previous files before checking them.", "保管した以前のファイルは、確認するまで削除しないでください。", "确认保留的原文件前，请勿删除它们。"],
  "일부 파일이 바뀌었습니다. 보존한 이전 파일을 확인하기 전에는 노드를 켜지 마세요.": ["Some files changed. Do not start the node before checking the preserved previous files.", "一部のファイルが変更されました。保管した以前のファイルを確認するまで、ノードを起動しないでください。", "部分文件已更改。确认保留的原文件前，请勿启动节点。"],

  "컴퓨터 간 직접 이사는 호환성 점검 중입니다. 암호화한 백업 파일을 USB로 옮긴 뒤 새 컴퓨터에서 되돌리기를 사용하세요.": ["Direct computer transfer is undergoing compatibility checks. Copy an encrypted backup to USB, then restore it on the new computer.", "コンピュータ間の直接移行は互換性を確認中です。暗号化したバックアップをUSBで移し、新しいコンピュータで復元してください。", "电脑间直接迁移正在进行兼容性检查。请通过 USB 复制加密备份，再在新电脑上恢复。"],
  "자동 백업의 로컬 사본에는 추가 암호화가 없습니다. 컴퓨터 계정과 디스크 잠금을 사용하세요. 직접 만든 백업 파일은 암호화합니다.": ["Local automatic backups have no additional encryption. Protect your computer account and disk. Manual backup files are encrypted.", "自動バックアップのローカルコピーは追加暗号化されません。アカウントとディスクを保護してください。手動バックアップは暗号化されます。", "自动备份的本地副本没有额外加密。请保护电脑账户并加密磁盘。手动备份文件会加密。"],
  "백업을 열려면 백업 암호 또는 백업 열쇠가 필요합니다. 지갑 복구 단어와는 다릅니다. 백업 파일과 별도로 안전하게 보관하세요.": ["Opening a backup requires its backup password or backup key. These are different from wallet recovery words. Store them safely, separately from the backup file.", "バックアップを開くには専用のパスワードまたはキーが必要です。ウォレットの復元単語とは異なります。ファイルとは別の安全な場所に保管してください。", "打开备份需要备份密码或备份密钥，与钱包助记词不同。请将其与备份文件分开安全保管。"],

  "지갑을 포함한 백업을 검증하고 잠갔습니다": ["Wallet backup verified and encrypted", "ウォレットを含むバックアップを検証し、暗号化しました", "已验证并加密包含钱包的备份"],
  "아래 파일을 담았습니다. 백업 파일과 백업 암호 또는 백업 열쇠를 별도로 보관하세요.": ["The files below are included. Store the backup file separately from its backup password or backup key.", "以下のファイルを保存しました。バックアップファイルとバックアップ用のパスワードまたはキーは別々に保管してください。", "包含以下文件。请将备份文件与备份密码或备份密钥分开保管。"],
  "브라우저·PWA 지갑과 파일, IPFS 원본, AI API 키는 이 백업에 포함되지 않습니다.": ["Browser and PWA wallets and files, original IPFS files, and AI API keys are not included in this backup.", "ブラウザ・PWAのウォレットとファイル、IPFSの元ファイル、AI APIキーはこのバックアップに含まれません。", "此备份不包含浏览器及 PWA 钱包和文件、IPFS 原始文件或 AI API 密钥。"],
  "지갑이 포함된 백업을 확인하지 못했습니다. 노드 연결을 확인한 뒤 다시 백업하세요.": ["Could not verify that the backup includes your wallet. Check the node connection and back up again.", "ウォレットを含むバックアップを確認できませんでした。ノードの接続を確認し、再度バックアップしてください。", "无法确认备份包含钱包。请检查节点连接，然后重新备份。"],
  "자동 백업을 확인하지 못했습니다. 노드 연결을 확인하고 백업을 다시 실행하세요.": ["Could not verify the automatic backup. Check the node connection and run the backup again.", "自動バックアップを確認できませんでした。ノードの接続を確認し、再度バックアップしてください。", "无法确认自动备份。请检查节点连接并重新运行备份。"],

  "같은 HTTPS 주소에서 키 칸을 비우면 기존 키를 유지합니다. 주소를 바꾸면 키를 다시 입력하세요. 삭제는 위의 지우기 단추를 누르세요.": ["An empty key field keeps the existing key only at the same HTTPS address. Re-enter the key when changing the address. Use Delete above to remove it.", "同じ HTTPS アドレスでは、キー欄を空にすると保存済みのキーを維持します。アドレス変更時はキーを入力し直してください。削除するには上の「削除」を押してください。", "仅在 HTTPS 地址不变时，密钥栏留空才会保留原有密钥。更改地址后请重新输入密钥。如需移除，请点击上方的删除按钮。"],
  "브라우저를 열지 못했습니다. 주소창에 ravenvault.ex.erci.se/wallet/를 입력하세요.": ["Could not open the browser. Enter ravenvault.ex.erci.se/wallet/ in its address bar.", "ブラウザを開けませんでした。アドレス欄に ravenvault.ex.erci.se/wallet/ を入力してください。", "无法打开浏览器。请在地址栏输入 ravenvault.ex.erci.se/wallet/。"],
  "HTTP는 이 컴퓨터 또는 사설망의 무키 AI만 허용합니다. 로컬 AI를 선택하면 실패해도 클라우드로 질문을 넘기지 않습니다.": ["HTTP is allowed only for AI without a key on this computer or a private network. Selecting local AI keeps questions there even if it fails.", "HTTP は、このコンピュータまたはプライベートネットワーク上のキー不要の AI に限り使えます。ローカル AI を選ぶと、失敗しても質問をクラウドに送りません。", "HTTP 仅可用于本机或私有网络上无需密钥的 AI。选择本地 AI 后，即使失败也不会将问题转发到云端。"],
  "AI 주소를 다시 입력하세요. HTTPS 또는 로컬 HTTP 주소를 사용하세요.": ["Enter the AI address again. Use HTTPS or a local HTTP address.", "AI のアドレスを入力し直してください。HTTPS またはローカル HTTP を使ってください。", "请重新输入 AI 地址，使用 HTTPS 或本地 HTTP 地址。"],
  "AI 서버에 설치된 모델 이름을 입력하세요.": ["Enter the name of a model installed on the AI server.", "AI サーバーにインストールしたモデル名を入力してください。", "请输入 AI 服务器上已安装的模型名称。"],
  "API 키를 줄바꿈 없이 다시 입력하세요.": ["Enter the API key again without line breaks.", "API キーを改行なしで入力し直してください。", "请重新输入 API 密钥，不要包含换行。"],
  "AI 주소에서 아이디·비밀번호·물음표 뒤 값을 빼고 다시 저장하세요.": ["Remove credentials and query values from the AI address, then save again.", "AI のアドレスから ID・パスワード・クエリを削除し、保存し直してください。", "请从 AI 地址中移除账号、密码和查询参数，然后重新保存。"],
  "HTTP는 로컬·사설망의 키 없는 AI만 사용할 수 있습니다. 원격 AI는 HTTPS로 바꾸세요.": ["HTTP is only for local or private-network AI without an API key. Use HTTPS for remote AI.", "HTTP はローカル・プライベートネットワーク上のキー不要 AI に限ります。リモート AI は HTTPS に変更してください。", "HTTP 仅适用于本机或私有网络上无需 API 密钥的 AI。远程 AI 请改用 HTTPS。"],
  "AI 연결을 준비하지 못했습니다. 앱을 다시 열어 주세요.": ["Could not prepare the AI connection. Reopen the app.", "AI 接続を準備できませんでした。アプリを開き直してください。", "无法准备 AI 连接。请重新打开应用。"],
  "이전 API 키를 지우지 못했습니다. 설정 폴더 권한을 확인하세요.": ["Could not remove the previous API key. Check the settings folder permissions.", "以前の API キーを削除できませんでした。設定フォルダーの権限を確認してください。", "无法删除之前的 API 密钥。请检查设置文件夹的权限。"],
  "AI 설정을 저장하지 못했습니다. 설정 폴더 권한과 여유 공간을 확인하세요.": ["Could not save AI settings. Check the settings folder permissions and free space.", "AI 設定を保存できませんでした。設定フォルダーの権限と空き容量を確認してください。", "无法保存 AI 设置。请检查设置文件夹权限和可用空间。"],
  "AI 설정을 다시 저장해 주세요.": ["Save the AI settings again.", "AI 設定を保存し直してください。", "请重新保存 AI 设置。"],
};
