/** Korean source copy + English, Japanese and Simplified Chinese. User text is not translated here. */
export const DESKTOP_COPY: Record<string, [string, string, string]> = {
  "같은 HTTPS 주소에서 키 칸을 비우면 기존 키를 유지합니다. 주소를 바꾸면 키를 다시 입력하세요. 삭제는 위의 지우기 단추를 누르세요.": ["An empty key field keeps the existing key only at the same HTTPS address. Re-enter the key when changing the address. Use Delete above to remove it.", "同じ HTTPS アドレスでは、キー欄を空にすると保存済みのキーを維持します。アドレス変更時はキーを入力し直してください。削除するには上の「削除」を押してください。", "仅在 HTTPS 地址不变时，密钥栏留空才会保留原有密钥。更改地址后请重新输入密钥。如需移除，请点击上方的删除按钮。"],
  "RavenVault 웹 지갑": ["RavenVault web wallet", "RavenVault ウェブウォレット", "RavenVault 网页钱包"],
  "웹 지갑 · 파일": ["Web wallet · Files", "ウェブウォレット・ファイル", "网页钱包 · 文件"],
  "오프라인 파일 · 음악 · 문서": ["Offline files · Music · Documents", "オフラインファイル・音楽・文書", "离线文件 · 音乐 · 文档"],
  "웹 지갑 · 오프라인 파일": ["Web wallet · Offline files", "ウェブウォレット・オフラインファイル", "网页钱包 · 离线文件"],
  "웹 지갑은 브라우저에 별도로 저장됩니다. Desktop 지갑과 기존 쪽지·결제 지갑은 그대로 사용합니다.": ["The web wallet is stored separately in your browser. Your Desktop wallet and existing message and payment wallet remain available.", "ウェブウォレットはブラウザに別途保存されます。Desktop ウォレットと従来のメッセージ・決済ウォレットも引き続き使えます。", "网页钱包单独保存在浏览器中。Desktop 钱包及现有私信和支付钱包仍可照常使用。"],
  "처음 한 번 인터넷으로 열어 설치하고 파일을 가져오세요. 보관한 음악·영상·문서는 오프라인에서 열 수 있습니다. 거래 확정에는 연결된 노드가 필요합니다.": ["Open it online once to install it and import files. Saved music, videos and documents can be opened offline. Confirming transactions requires a connected node.", "最初にオンラインで開いてインストールし、ファイルを取り込んでください。保存した音楽・動画・文書はオフラインで開けます。取引の確定には接続されたノードが必要です。", "首次联网打开并安装，然后导入文件。保存的音乐、视频和文档可离线打开。交易确认需要连接节点。"],
  "같은 컴퓨터의 노드를 연결하려면 웹 지갑 설정에 http://127.0.0.1:8790을 입력하세요. 노드와 손님 서버가 켜져 있어야 합니다.": ["To use this computer's node, enter http://127.0.0.1:8790 in web wallet settings. The node and customer server must be running.", "このコンピュータのノードを使うには、ウェブウォレットの設定に http://127.0.0.1:8790 を入力してください。ノードとお客様用サーバーの起動が必要です。", "要连接本机节点，请在网页钱包设置中输入 http://127.0.0.1:8790。节点和顾客服务器必须处于运行状态。"],
  "브라우저에 RavenVault를 열었습니다. 파일을 가져온 뒤 오프라인에서 다시 열어 확인하세요.": ["Opened RavenVault in your browser. Import files, then reopen it offline to check they are available.", "ブラウザで RavenVault を開きました。ファイルを取り込み、オフラインでも開けることを確認してください。", "已在浏览器中打开 RavenVault。导入文件后，请离线重新打开以确认可用。"],
  "브라우저를 열지 못했습니다. 주소창에 ravenvault.ex.erci.se/wallet/를 입력하세요.": ["Could not open the browser. Enter ravenvault.ex.erci.se/wallet/ in its address bar.", "ブラウザを開けませんでした。アドレス欄に ravenvault.ex.erci.se/wallet/ を入力してください。", "无法打开浏览器。请在地址栏输入 ravenvault.ex.erci.se/wallet/。"],
  "RavenVault 홈페이지": ["RavenVault website", "RavenVault ホームページ", "RavenVault 网站"],
  "HTTP는 이 컴퓨터 또는 사설망의 무키 AI만 허용합니다. 로컬 AI를 선택하면 실패해도 클라우드로 질문을 넘기지 않습니다.": ["HTTP is allowed only for AI without a key on this computer or a private network. Selecting local AI keeps questions there even if it fails.", "HTTP は、このコンピュータまたはプライベートネットワーク上のキー不要の AI に限り使えます。ローカル AI を選ぶと、失敗しても質問をクラウドに送りません。", "HTTP 仅可用于本机或私有网络上无需密钥的 AI。选择本地 AI 后，即使失败也不会将问题转发到云端。"],
  "AI 주소를 다시 입력하세요. HTTPS 또는 로컬 HTTP 주소를 사용하세요.": ["Enter the AI address again. Use HTTPS or a local HTTP address.", "AI のアドレスを入力し直してください。HTTPS またはローカル HTTP を使ってください。", "请重新输入 AI 地址，使用 HTTPS 或本地 HTTP 地址。"],
  "AI 서버에 설치된 모델 이름을 입력하세요.": ["Enter the name of a model installed on the AI server.", "AI サーバーにインストールしたモデル名を入力してください。", "请输入 AI 服务器上已安装的模型名称。"],
  "API 키를 줄바꿈 없이 다시 입력하세요.": ["Enter the API key again without line breaks.", "API キーを改行なしで入力し直してください。", "请重新输入 API 密钥，不要包含换行。"],
  "AI 주소에서 아이디·비밀번호·물음표 뒤 값을 빼고 다시 저장하세요.": ["Remove credentials and query values from the AI address, then save again.", "AI のアドレスから ID・パスワード・クエリを削除し、保存し直してください。", "请从 AI 地址中移除账号、密码和查询参数，然后重新保存。"],
  "HTTP는 로컬·사설망의 키 없는 AI만 사용할 수 있습니다. 원격 AI는 HTTPS로 바꾸세요.": ["HTTP is only for local or private-network AI without an API key. Use HTTPS for remote AI.", "HTTP はローカル・プライベートネットワーク上のキー不要 AI に限ります。リモート AI は HTTPS に変更してください。", "HTTP 仅适用于本机或私有网络上无需 API 密钥的 AI。远程 AI 请改用 HTTPS。"],
  "AI 연결을 준비하지 못했습니다. 앱을 다시 열어 주세요.": ["Could not prepare the AI connection. Reopen the app.", "AI 接続を準備できませんでした。アプリを開き直してください。", "无法准备 AI 连接。请重新打开应用。"],
  "이전 API 키를 지우지 못했습니다. 설정 폴더 권한을 확인하세요.": ["Could not remove the previous API key. Check the settings folder permissions.", "以前の API キーを削除できませんでした。設定フォルダーの権限を確認してください。", "无法删除之前的 API 密钥。请检查设置文件夹的权限。"],
  "AI 설정을 저장하지 못했습니다. 설정 폴더 권한과 여유 공간을 확인하세요.": ["Could not save AI settings. Check the settings folder permissions and free space.", "AI 設定を保存できませんでした。設定フォルダーの権限と空き容量を確認してください。", "无法保存 AI 设置。请检查设置文件夹权限和可用空间。"],
  "AI 설정을 다시 저장해 주세요.": ["Save the AI settings again.", "AI 設定を保存し直してください。", "请重新保存 AI 设置。"],
};
