/** Korean source copy + English, Japanese and Simplified Chinese. User text is not translated here. */
export const DESKTOP_COPY: Record<string, [string, string, string]> = {
  "없음": ["None", "なし", "无"],
  "메인넷 노드의 연결과 동기화 상태를 확인하세요.": ["Check the mainnet node connection and sync status.", "メインネットのノードの接続と同期状態を確認してください。", "请检查主网节点的连接和同步状态。"],
  "내 노드로 조회하고, 폰에서 서명한 거래를 보냅니다.": ["Look up the chain through your node and send transactions signed on your phone.", "自分のノードで照会し、スマートフォンで署名した取引を送信します。", "通过自己的节点查询，并发送手机上已签名的交易。"],
  "분할 QR은 모든 조각을 한 줄에 하나씩 붙여넣으세요.": ["For a split QR, paste every part on its own line.", "分割 QR は、全ての断片を1行ずつ貼り付けてください。", "对于分段二维码，请每行粘贴一个片段，包含全部片段。"],
  "거래 조각이 부족합니다. 모든 조각을 한 줄에 하나씩 붙여넣으세요.": ["Transaction parts are missing. Paste every part on its own line.", "取引の断片が足りません。全ての断片を1行ずつ貼り付けてください。", "交易片段不完整。请每行粘贴一个片段，包含全部片段。"],
  "폰에서 RavenVault 쓰기": ["Use RavenVault on your phone", "スマートフォンで RavenVault を使う", "在手机上使用 RavenVault"],
  "폰에서 서명한 거래 보내기": ["Send a transaction signed on your phone", "スマートフォンで署名した取引を送信", "发送手机已签名的交易"],
  "열쇠는 폰에, 전파는 내 노드로": ["Keys on your phone, relay through your node", "鍵はスマートフォンに、送信は自分のノードから", "密钥留在手机，通过自己的节点广播"],
  "물어보고 시키는 곳. AI는 직접 켤 때만 사용합니다.": ["Ask questions and give instructions. AI runs only when you enable it.", "質問や指示をする場所です。AI は自分で有効にした場合のみ使います。", "在这里提问和发出指令。AI 仅在您主动启用时使用。"],
  "열쇠는 폰에 남습니다. 이 컴퓨터는 내용을 확인하고 내 노드로 전파합니다.": ["Keys stay on your phone. This computer reviews the transaction and relays it through your node.", "鍵はスマートフォンに残ります。このコンピュータで内容を確認し、自分のノードから送信します。", "密钥留在手机上。此电脑检查交易内容，并通过您的节点广播。"],
  "폰의 서명 거래 코드 붙여넣기": ["Paste the signed transaction code from your phone", "スマートフォンの署名済み取引コードを貼り付け", "粘贴手机上的已签名交易代码"],
  "보내기 전 내용 확인": ["Review before sending", "送信前に内容を確認", "发送前检查内容"],
  "입력 지우기": ["Clear input", "入力を消去", "清除输入"],
  "확인하고 네트워크에 보내기": ["Confirm and send to the network", "確認してネットワークに送信", "确认并发送到网络"],
  "폰 카메라로 찍으면 RavenVault가 열립니다. 폰 지갑과 이 컴퓨터의 지갑은 별개이며 잔액이 자동으로 합쳐지지 않습니다.": ["Scan with your phone camera to open RavenVault. The phone and computer wallets are separate; balances do not merge automatically.", "スマートフォンのカメラで読み取ると RavenVault が開きます。スマートフォンとコンピュータのウォレットは別々で、残高は自動で統合されません。", "用手机摄像头扫描即可打开 RavenVault。手机钱包和电脑钱包彼此独立，余额不会自动合并。"],
  "브라우저로 열기": ["Open in browser", "ブラウザで開く", "在浏览器中打开"],
  "같은 컴퓨터의 Chrome에서 http://127.0.0.1:8790에 연결할 때는 로컬 네트워크 접근을 허용해야 합니다. 노드와 손님 서버가 켜져 있어야 합니다.": ["In Chrome on this computer, connecting to http://127.0.0.1:8790 requires Local Network Access permission. The node and customer server must be running.", "このコンピュータの Chrome で http://127.0.0.1:8790 に接続するには、ローカルネットワークへのアクセスを許可してください。ノードとお客様用サーバーの起動が必要です。", "在此电脑的 Chrome 中连接 http://127.0.0.1:8790 时，需要允许本地网络访问。节点和顾客服务器必须正在运行。"],
  "다른 기기에서는 127.0.0.1로 이 컴퓨터에 연결할 수 없습니다. 폰에서는 접근 가능한 이 컴퓨터의 노드 주소를 설정하세요.": ["Other devices cannot reach this computer at 127.0.0.1. On your phone, configure a reachable node address for this computer.", "他の端末から 127.0.0.1 でこのコンピュータには接続できません。スマートフォンには、このコンピュータに接続可能なノードのアドレスを設定してください。", "其他设备无法通过 127.0.0.1 连接此电脑。请在手机上设置可访问的此电脑节点地址。"],
  "브라우저에 RavenVault를 열었습니다.": ["Opened RavenVault in your browser.", "ブラウザで RavenVault を開きました。", "已在浏览器中打开 RavenVault。"],
  "QR을 만들지 못했습니다. 아래 주소를 폰에서 열어 주세요.": ["Could not create the QR code. Open the address below on your phone.", "QR コードを作成できませんでした。下のアドレスをスマートフォンで開いてください。", "无法生成二维码。请在手机上打开下方地址。"],
  "거래 코드의 형식·버전·길이를 확인하세요. 폰에서 서명한 거래 코드를 다시 복사하세요.": ["Check the transaction code format, version and length. Copy the signed transaction code from your phone again.", "取引コードの形式・バージョン・長さを確認し、スマートフォンの署名済みコードをコピーし直してください。", "请检查交易代码的格式、版本和长度，并重新复制手机上的已签名交易代码。"],
  "거래 내용을 확인하는 중입니다. 아직 보내지 않았습니다.": ["Reviewing the transaction. It has not been sent.", "取引内容を確認中です。まだ送信していません。", "正在检查交易内容，尚未发送。"],
  "거래 ID": ["Transaction ID", "取引 ID", "交易 ID"],
  "출력 안내": ["About outputs", "出力について", "输出说明"],
  "거스름돈을 포함한 모든 출력입니다. 받는 사람과 거스름돈은 자동으로 구분하지 못합니다.": ["All outputs are shown, including change. Recipient and change outputs cannot be distinguished automatically.", "お釣りを含む全出力です。受取先とお釣りは自動では区別できません。", "这里显示包含找零的全部输出，无法自动区分收款和找零。"],
  "출력": ["Output", "出力", "输出"],
  "받는 주소": ["Recipient address", "受取先アドレス", "收款地址"],
  "RVN 금액": ["RVN amount", "RVN 金額", "RVN 金额"],
  "자산": ["Asset", "資産", "资产"],
  "수수료": ["Fee", "手数料", "手续费"],
  "확인 못 함": ["Unable to verify", "確認できません", "无法确认"],
  "아직 보내지 않았습니다. 폰의 내용과 대조한 뒤 확인하고 보내세요.": ["Not sent yet. Compare with your phone, then confirm and send.", "まだ送信していません。スマートフォンの内容と照合し、確認して送信してください。", "尚未发送。请与手机上的内容核对，然后确认发送。"],
  "네트워크에 보내는 중입니다.": ["Sending to the network.", "ネットワークに送信中です。", "正在发送到网络。"],
  "노드가 거래를 받았습니다. 블록 확정은 아직 확인 못 함.": ["The node accepted the transaction. Block confirmation has not yet been verified.", "ノードが取引を受け付けました。ブロックでの確定はまだ確認できません。", "节点已接受交易，尚未确认是否已在区块中确认。"],
  "전파 결과를 확인 못 했습니다. 다시 보내기 전에 거래 ID로 확인하세요.": ["Could not verify the relay result. Check the transaction ID before sending again.", "送信結果を確認できませんでした。再送信の前に取引 ID で確認してください。", "无法确认广播结果。再次发送前，请通过交易 ID 查询。"],
  "노드에 연결하지 못했습니다. 이 컴퓨터에서 노드 상태를 확인하세요.": ["Could not connect to the node. Check its status on this computer.", "ノードに接続できませんでした。このコンピュータで状態を確認してください。", "无法连接节点。请在此电脑上检查节点状态。"],
  "메인넷 노드와 메인넷 받는 주소만 사용할 수 있습니다.": ["Only a mainnet node and mainnet recipient addresses are supported.", "メインネットのノードと受取先アドレスのみ使用できます。", "仅支持主网节点和主网收款地址。"],
  "노드가 동기화 중입니다. 완료한 뒤 다시 확인하세요.": ["The node is syncing. Review again once it finishes.", "ノードは同期中です。完了後に再度確認してください。", "节点正在同步，请完成后重试。"],
  "이미 네트워크에 알려진 거래입니다. 거래 ID로 확인하세요.": ["This transaction is already known to the network. Check its transaction ID.", "ネットワークで既知の取引です。取引 ID で確認してください。", "网络已知此交易。请通过交易 ID 查询。"],
  "입력을 찾을 수 없습니다. 이미 사용했거나 아직 노드가 확인하지 못한 입력입니다.": ["Inputs are unavailable. They may be spent or not yet known to the node.", "入力が見つかりません。使用済み、またはノードがまだ確認できていない可能性があります。", "找不到输入，可能已花费或节点尚未确认。"],
  "노드가 거래를 거부했습니다. 서명·잔액·수수료를 폰에서 다시 확인하세요.": ["The node rejected the transaction. Recheck the signature, balance and fee on your phone.", "ノードが取引を拒否しました。スマートフォンで署名・残高・手数料を再確認してください。", "节点拒绝了交易。请在手机上重新检查签名、余额和手续费。"],
  "거래 내용을 확인한 뒤 보내기 단추를 눌러 주세요.": ["Review the transaction, then press Send.", "取引内容を確認してから送信ボタンを押してください。", "请确认交易内容后再按发送按钮。"],

  "폴더에서 되돌리기": ["Restore from folder", "フォルダーから復元", "从文件夹恢复"],
  "되돌릴 백업 폴더를 고르세요": ["Choose a backup folder to restore", "復元するバックアップフォルダーを選んでください", "请选择要恢复的备份文件夹"],

  "되돌리기를 완료했습니다": ["Restore completed", "復元が完了しました", "恢复已完成"],
  "일부만 되돌렸습니다": ["Only some items were restored", "一部の項目のみ復元しました", "仅恢复了部分项目"],
  "되돌리기를 완료하지 못했습니다": ["Restore did not complete", "復元を完了できませんでした", "未能完成恢复"],
  "보존한 이전 파일을 확인하기 전에는 지우지 마세요.": ["Do not delete the preserved previous files before checking them.", "保管した以前のファイルは、確認するまで削除しないでください。", "确认保留的原文件前，请勿删除它们。"],
  "일부 파일이 바뀌었습니다. 보존한 이전 파일을 확인하기 전에는 노드를 켜지 마세요.": ["Some files changed. Do not start the node before checking the preserved previous files.", "一部のファイルが変更されました。保管した以前のファイルを確認するまで、ノードを起動しないでください。", "部分文件已更改。确认保留的原文件前，请勿启动节点。"],

  "컴퓨터 간 직접 이사는 호환성 점검 중입니다. 암호화한 백업 파일을 USB로 옮긴 뒤 새 컴퓨터에서 되돌리기를 사용하세요.": ["Direct computer transfer is undergoing compatibility checks. Copy an encrypted backup to USB, then restore it on the new computer.", "コンピュータ間の直接移行は互換性を確認中です。暗号化したバックアップをUSBで移し、新しいコンピュータで復元してください。", "电脑间直接迁移正在进行兼容性检查。请通过 USB 复制加密备份，再在新电脑上恢复。"],
  "자동 백업의 로컬 사본에는 추가 암호화가 없습니다. 컴퓨터 계정과 디스크 잠금을 사용하세요. 직접 만든 백업 파일은 암호화합니다.": ["Local automatic backups have no additional encryption. Protect your computer account and disk. Manual backup files are encrypted.", "自動バックアップのローカルコピーは追加暗号化されません。アカウントとディスクを保護してください。手動バックアップは暗号化されます。", "自动备份的本地副本没有额外加密。请保护电脑账户并加密磁盘。手动备份文件会加密。"],
  "백업을 열려면 백업 암호 또는 백업 열쇠가 필요합니다. 지갑 복구 단어와는 다릅니다. 백업 파일과 별도로 안전하게 보관하세요.": ["Opening a backup requires its backup password or backup key. These are different from wallet recovery words. Store them safely, separately from the backup file.", "バックアップを開くには専用のパスワードまたはキーが必要です。ウォレットの復元単語とは異なります。ファイルとは別の安全な場所に保管してください。", "打开备份需要备份密码或备份密钥，与钱包助记词不同。请将其与备份文件分开安全保管。"],

  "지갑을 포함한 백업을 검증하고 잠갔습니다": ["Wallet backup verified and encrypted", "ウォレットを含むバックアップを検証し、暗号化しました", "已验证并加密包含钱包的备份"],
  "아래 파일을 담았습니다. 백업 파일과 백업 암호 또는 백업 열쇠를 별도로 보관하세요.": ["The files below are included. Store the backup file separately from its backup password or backup key.", "以下のファイルを保存しました。バックアップファイルとバックアップ用のパスワードまたはキーは別々に保管してください。", "包含以下文件。请将备份文件与备份密码或备份密钥分开保管。"],
  "브라우저·PWA 지갑과 파일, IPFS 원본, AI API 키는 이 백업에 포함되지 않습니다.": ["Browser and PWA wallets and files, original IPFS files, and AI API keys are not included in this backup.", "ブラウザ・PWAのウォレットとファイル、IPFSの元ファイル、AI APIキーはこのバックアップに含まれません。", "此备份不包含浏览器及 PWA 钱包和文件、IPFS 原始文件或 AI API 密钥。"],
  "지갑이 포함된 백업을 확인하지 못했습니다. 노드 연결을 확인한 뒤 다시 백업하세요.": ["Could not verify that the backup includes your wallet. Check the node connection and back up again.", "ウォレットを含むバックアップを確認できませんでした。ノードの接続を確認し、再度バックアップしてください。", "无法确认备份包含钱包。请检查节点连接，然后重新备份。"],
  "자동 백업을 확인하지 못했습니다. 노드 연결을 확인하고 백업을 다시 실행하세요.": ["Could not verify the automatic backup. Check the node connection and run the backup again.", "自動バックアップを確認できませんでした。ノードの接続を確認し、再度バックアップしてください。", "无法确认自动备份。请检查节点连接并重新运行备份。"],

  "같은 HTTPS 주소에서 키 칸을 비우면 기존 키를 유지합니다. 주소를 바꾸면 키를 다시 입력하세요. 삭제는 위의 지우기 단추를 누르세요.": ["An empty key field keeps the existing key only at the same HTTPS address. Re-enter the key when changing the address. Use Delete above to remove it.", "同じ HTTPS アドレスでは、キー欄を空にすると保存済みのキーを維持します。アドレス変更時はキーを入力し直してください。削除するには上の「削除」を押してください。", "仅在 HTTPS 地址不变时，密钥栏留空才会保留原有密钥。更改地址后请重新输入密钥。如需移除，请点击上方的删除按钮。"],
  "브라우저를 열지 못했습니다. 주소창에 ravenvault.ex.erci.se/wallet/를 입력하세요.": ["Could not open the browser. Enter ravenvault.ex.erci.se/wallet/ in its address bar.", "ブラウザを開けませんでした。アドレス欄に ravenvault.ex.erci.se/wallet/ を入力してください。", "无法打开浏览器。请在地址栏输入 ravenvault.ex.erci.se/wallet/。"],
  "HTTP는 이 컴퓨터 또는 사설망의 무키 AI만 허용합니다. 로컬 AI를 선택하면 실패해도 클라우드로 질문을 넘기지 않습니다.": ["HTTP is allowed only for AI without a key on this computer or a private network. Selecting local AI keeps questions there even if it fails.", "HTTP は、このコンピュータまたはプライベートネットワーク上のキー不要の AI に限り使えます。ローカル AI を選ぶと、失敗しても質問をクラウドに送りません。", "HTTP 仅可用于本机或私有网络上无需密钥的 AI。选择本地 AI 后，即使失败也不会将问题转发到云端。"],
  "AI 주소를 다시 입력하세요. HTTPS 또는 로컬 HTTP 주소를 사용하세요.": ["Enter the AI address again. Use HTTPS or a local HTTP address.", "AI のアドレスを入力し直してください。HTTPS またはローカル HTTP を使ってください。", "请重新输入 AI 地址，使用 HTTPS 或本地 HTTP 地址。"],
  "AI 서버에 설치된 모델 이름을 입력하세요.": ["Enter the name of a model installed on the AI server.", "AI サーバーにインストールしたモデル名を入力してください。", "请输入 AI 服务器上已安装的模型名称。"],
  "API 키를 줄바꿈 없이 다시 입력하세요.": ["Enter the API key again without line breaks.", "API キーを改行なしで入力し直してください。", "请重新输入 API 密钥，不要包含换行。"],
  "AI 주소에서 아이디·비밀번호·물음표 뒤 값을 빼고 다시 저장하세요.": ["Remove credentials and query values from the AI address, then save again.", "AI のアドレスから ID・パスワード・クエリを削除し、保存し直してください。", "请从 AI 地址中移除账号、密码和查询参数，然后重新保存。"],
  "HTTP는 로컬·사설망의 키 없는 AI만 사용할 수 있습니다. 원격 AI는 HTTPS로 바꾸세요.": ["HTTP is only for local or private-network AI without an API key. Use HTTPS for remote AI.", "HTTP はローカル・プライベートネットワーク上のキー不要 AI に限ります。リモート AI は HTTPS に変更してください。", "HTTP 仅适用于本机或私有网络上无需 API 密钥的 AI。远程 AI 请改用 HTTPS。"],
  "AI 연결을 준비하지 못했습니다. 앱을 다시 열어 주세요.": ["Could not prepare the AI connection. Reopen the app.", "AI 接続を準備できませんでした。アプリを開き直してください。", "无法准备 AI 连接。请重新打开应用。"],
  "이전 API 키를 지우지 못했습니다. 설정 폴더 권한을 확인하세요.": ["Could not remove the previous API key. Check the settings folder permissions.", "以前の API キーを削除できませんでした。設定フォルダーの権限を確認してください。", "无法删除之前的 API 密钥。请检查设置文件夹的权限。"],
  "AI 설정을 저장하지 못했습니다. 설정 폴더 권한과 여유 공간을 확인하세요.": ["Could not save AI settings. Check the settings folder permissions and free space.", "AI 設定を保存できませんでした。設定フォルダーの権限と空き容量を確認してください。", "无法保存 AI 设置。请检查设置文件夹权限和可用空间。"],
  "AI 설정을 다시 저장해 주세요.": ["Save the AI settings again.", "AI 設定を保存し直してください。", "请重新保存 AI 设置。"],
};
