/* 「지도에 올리기」 문구 — [영어, 일본어, 중국어]. 열쇠는 한국어 원문 그대로(i18n.ts 와 같은 방식).
 * 이미 사전에 있는 같은 한국어는 덮지 않는다(dict.ts 에서 ??= 로 넣는다).
 * scripts/check-map-copy.mjs 가 화면·코드의 한국어가 여기(또는 사전)에 다 있는지 본다. */
export const MAP_COPY: Record<string, [string, string, string]> = {
  // 카드
  "지도에 올리기": ["Put on the map", "地図に載せる", "放到地图上"],
  "손님 폰 지도에 내 가게가 보이고, 이 컴퓨터가 켜져 있는 동안 「영업 중」으로 뜹니다.": ["Your shop appears on customers' phone maps, and shows as “Open” while this computer is on.", "お客様のスマホの地図にお店が表示され、このコンピュータが起動している間は「営業中」と表示されます。", "您的店铺会出现在顾客手机地图上，这台电脑开着时显示为“营业中”。"],
  "지도에 올라가는 것은 가게 이름·업종·동네(약 5km 칸)·가게 링크·영업 중 신호뿐입니다. 정확한 주소와 좌표는 보내지 않습니다.": ["Only the shop name, category, neighbourhood (a square of about 5 km), shop link and the open signal go on the map. The exact address and coordinates are never sent.", "地図に載るのは店名・業種・地域（約5kmの区画）・お店のリンク・営業中の信号だけです。正確な住所や座標は送りません。", "放到地图上的只有店名、类别、街区（约5公里的方格）、店铺链接和营业信号。不会发送确切地址和坐标。"],
  "가게 이름": ["Shop name", "店名", "店名"],
  "업종": ["Category", "業種", "类别"],
  "동네": ["Neighbourhood", "地域", "街区"],
  "동네 이름으로 찾기 — 예: 내손동, 분당": ["Search by neighbourhood — e.g. Naeson-dong, Bundang", "地域名で探す — 例: 内蓀洞、盆唐", "按街区名搜索 — 例如：内荪洞、盆唐"],
  "지역 코드 직접 넣기": ["Enter an area code yourself", "地域コードを直接入力", "直接输入地区代码"],
  "5자리 지역 코드 — 예: wydk3": ["5-character area code — e.g. wydk3", "5文字の地域コード — 例: wydk3", "5位地区代码 — 例如：wydk3"],
  "표에 없는 동네는 5자리 지역 코드(geohash)를 넣으세요. 더 긴 코드(정확한 위치)는 받지 않습니다.": ["For a neighbourhood not in the list, enter its 5-character area code (geohash). Longer codes (exact locations) are not accepted.", "一覧にない地域は5文字の地域コード（geohash）を入力してください。それより長いコード（正確な位置）は受け付けません。", "列表中没有的街区，请输入5位地区代码（geohash）。更长的代码（精确位置）不接受。"],
  "표에 없는 동네예요. 아래 「지역 코드 직접 넣기」를 써 주세요.": ["That neighbourhood is not in the list. Use “Enter an area code yourself” below.", "一覧にない地域です。下の「地域コードを直接入力」を使ってください。", "列表中没有这个街区。请使用下方的“直接输入地区代码”。"],
  "가게 링크": ["Shop link", "お店のリンク", "店铺链接"],
  "지금 바깥 연결 주소 넣기": ["Use the current outside-access address", "今の外部接続アドレスを入れる", "填入当前的外部连接地址"],
  "고정 이름 터널 만드는 법": ["How to set up a named (fixed) tunnel", "固定名トンネルの作り方", "如何建立固定名称隧道"],
  "임시 주소(…trycloudflare.com)는 앱이나 터널을 다시 켤 때마다 바뀝니다. 내 도메인이 있으면 Cloudflare 의 「이름 있는 터널」로 주소를 고정할 수 있습니다: ① cloudflared tunnel login ② cloudflared tunnel create 가게이름 ③ cloudflared tunnel route dns 가게이름 shop.내도메인 ④ 그 터널을 이 컴퓨터의 8790 포트로 연결 ⑤ https://shop.내도메인 을 위 「가게 링크」에 넣기. 어려우시면 「문제 알리기」로 물어 주세요.": ["A temporary address (…trycloudflare.com) changes every time the app or tunnel restarts. If you own a domain, a Cloudflare “named tunnel” keeps the address fixed: ① cloudflared tunnel login ② cloudflared tunnel create shopname ③ cloudflared tunnel route dns shopname shop.yourdomain ④ point that tunnel at port 8790 on this computer ⑤ put https://shop.yourdomain in “Shop link” above. If this is hard, ask through “Report a problem”.", "一時アドレス（…trycloudflare.com）はアプリやトンネルを再起動するたびに変わります。独自ドメインがあれば Cloudflare の「名前付きトンネル」でアドレスを固定できます: ① cloudflared tunnel login ② cloudflared tunnel create 店名 ③ cloudflared tunnel route dns 店名 shop.独自ドメイン ④ そのトンネルをこのコンピュータの8790番ポートにつなぐ ⑤ https://shop.独自ドメイン を上の「お店のリンク」に入れる。難しければ「問題を報告」でお尋ねください。", "临时地址（…trycloudflare.com）每次重启应用或隧道都会改变。如果您有自己的域名，可以用 Cloudflare 的“命名隧道”固定地址：① cloudflared tunnel login ② cloudflared tunnel create 店名 ③ cloudflared tunnel route dns 店名 shop.您的域名 ④ 将该隧道连到这台电脑的8790端口 ⑤ 把 https://shop.您的域名 填入上方“店铺链接”。如有困难，请通过“报告问题”询问。"],
  "올리기": ["Publish", "載せる", "发布"],
  "고친 내용 다시 올리기": ["Publish changes again", "変更をもう一度載せる", "重新发布修改"],
  "내리기": ["Take down", "取り下げる", "撤下"],
  "지도 서명 주소 — 이 컴퓨터의 가게 열쇠에서 나온 주소입니다. 손님 지도는 이 주소의 서명만 이 가게로 믿습니다.": ["Map signing address — derived from this computer's shop key. Customer maps trust only this address's signature as this shop.", "地図署名アドレス — このコンピュータのお店の鍵から作られたアドレスです。お客様の地図はこのアドレスの署名だけをこのお店として信頼します。", "地图签名地址 — 由这台电脑的店铺密钥生成。顾客地图只信任此地址的签名为本店。"],
  // 미리보기·상태
  "영업 신호": ["Open signal", "営業中の信号", "营业信号"],
  "이 컴퓨터가 켜져 있는 동안 5분마다": ["Every 5 minutes while this computer is on", "このコンピュータが起動している間、5分ごと", "这台电脑开着时每5分钟一次"],
  "약 5km 칸": ["about a 5 km square", "約5kmの区画", "约5公里方格"],
  "이름 없는 칸": ["Unnamed square", "名前のない区画", "未命名方格"],
  "없음": ["None", "なし", "无"],
  "임시 주소예요 — 재시작마다 바뀌어 지도에서 열리지 않아요. 켜져 있는 동안은 바뀐 주소로 다시 올리지만, 그 사이 손님은 헛걸음해요. 고정 이름 터널(내 도메인)을 쓰세요.": ["This is a temporary address — it changes on every restart and will not open from the map. While the app is on it republishes the new address, but customers hit a dead link in between. Use a named tunnel on your own domain.", "一時アドレスです — 再起動のたびに変わり、地図から開けなくなります。起動中は新しいアドレスで載せ直しますが、その間お客様は無駄足になります。固定名トンネル（独自ドメイン）を使ってください。", "这是临时地址 — 每次重启都会改变，从地图上打不开。应用开着时会用新地址重新发布，但在此期间顾客会白跑一趟。请使用自己域名的固定名称隧道。"],
  "가게 링크가 없으면 지도에는 보이지만 손님이 가게를 열 수 없어요. 「바깥 연결」을 켜거나 고정 주소를 넣어 주세요.": ["Without a shop link the shop shows on the map, but customers cannot open it. Turn on “Outside access” or enter a fixed address.", "お店のリンクがないと地図には表示されますが、お客様はお店を開けません。「外部接続」をオンにするか、固定アドレスを入れてください。", "没有店铺链接时，店铺会显示在地图上，但顾客无法打开。请开启“外部连接”或填入固定地址。"],
  "고정 주소예요. 손님 지도의 [가게 열기]가 이 주소를 엽니다.": ["This is a fixed address. “Open shop” on customer maps opens it.", "固定アドレスです。お客様の地図の［お店を開く］がこのアドレスを開きます。", "这是固定地址。顾客地图上的［打开店铺］会打开此地址。"],
  "지도: 올림": ["Map: on", "地図: 掲載中", "地图：已发布"],
  "지도: 안 올림": ["Map: off", "地図: 未掲載", "地图：未发布"],
  "지도: 올림 · 지금 닫음 — 손님 지도에는 「쉬는 중」으로 보여요": ["Map: on · closed now — customers see “Closed”", "地図: 掲載中 · 今は閉店 — お客様の地図では「休業中」と表示されます", "地图：已发布 · 现在关门 — 顾客地图显示“休息中”"],
  "지도: 올림 · 영업 중 신호 {0} 보냄": ["Map: on · open signal sent {0}", "地図: 掲載中 · 営業中の信号を{0}に送信", "地图：已发布 · 营业信号于{0}发送"],
  "지도: 올림 · 아직 신호를 못 보냈어요 — 5분마다 조용히 다시 해요": ["Map: on · signal not sent yet — retrying quietly every 5 minutes", "地図: 掲載中 · まだ信号を送れていません — 5分ごとに静かに再試行します", "地图：已发布 · 尚未发出信号 — 每5分钟静默重试"],
  "{0}분 전": ["{0} min ago", "{0}分前", "{0}分钟前"],
  "{0}시간 전": ["{0} h ago", "{0}時間前", "{0}小时前"],
  "올렸어요. 손님 지도에 곧 보입니다 — 이 컴퓨터가 켜져 있는 동안 「영업 중」으로 떠요.": ["Published. It will show on customer maps shortly — as “Open” while this computer is on.", "載せました。まもなくお客様の地図に表示されます — このコンピュータが起動している間は「営業中」です。", "已发布。很快会出现在顾客地图上 — 这台电脑开着时显示“营业中”。"],
  "지도에서 내릴까요? 손님 지도에서 가게와 「영업 중」 표시가 사라집니다.": ["Take the shop off the map? The shop and its “Open” mark will disappear from customer maps.", "地図から取り下げますか？お客様の地図からお店と「営業中」の表示が消えます。", "要从地图上撤下吗？店铺和“营业中”标记将从顾客地图上消失。"],
  "지도에서 내렸어요.": ["Taken off the map.", "地図から取り下げました。", "已从地图撤下。"],
  // 검사(폰과 같은 문구 · map_format.rs)
  "가게 주소 이름은 영문 소문자·숫자·- 로 2~40자여야 해요.": ["The shop's address name must be 2–40 lowercase letters, digits or -.", "お店のアドレス名は英小文字・数字・- で2〜40文字にしてください。", "店铺地址名须为2~40个小写字母、数字或 -。"],
  "가게 이름은 1~40자여야 해요.": ["The shop name must be 1–40 characters.", "店名は1〜40文字にしてください。", "店名须为1~40个字符。"],
  "업종을 골라 주세요.": ["Please choose a category.", "業種を選んでください。", "请选择类别。"],
  "동네는 5자리 지역 코드만 쓸 수 있어요. 정확한 위치는 받지 않아요.": ["Neighbourhoods use a 5-character area code only. Exact locations are not accepted.", "地域は5文字の地域コードだけ使えます。正確な位置は受け付けません。", "街区只能使用5位地区代码。不接受精确位置。"],
  "연락처는 80자 이하로 적어 주세요.": ["Keep the contact to 80 characters or fewer.", "連絡先は80文字以内で書いてください。", "联系方式请写在80个字符以内。"],
  "가게 링크는 https:// 로 시작해야 해요.": ["The shop link must start with https://.", "お店のリンクは https:// で始めてください。", "店铺链接必须以 https:// 开头。"],
  "시각이 올바르지 않아요.": ["The time is not valid.", "時刻が正しくありません。", "时间不正确。"],
  // 라비
  "지도에 올릴 내용을 채웠습니다 — 확인하고 [올리기]는 사장님이 누릅니다": ["Filled in what goes on the map — check it, then you press [Publish]", "地図に載せる内容を入力しました — 確認して［載せる］は店主様が押します", "已填好要放到地图上的内容 — 请确认，［发布］由店主按下"],
  "지도 올리기 준비를 못 했습니다 — 업종을 다시 말씀해 주세요": ["Could not prepare the map entry — please tell me the category again", "地図掲載の準備ができませんでした — 業種をもう一度教えてください", "未能准备地图发布 — 请再说一次类别"],
  "지도 올리기 준비를 못 했습니다 — 동네 표에 없는 동네입니다. 화면에서 직접 골라 주세요": ["Could not prepare the map entry — that neighbourhood is not in the list. Please choose it on the screen", "地図掲載の準備ができませんでした — 一覧にない地域です。画面で直接選んでください", "未能准备地图发布 — 该街区不在列表中。请在界面上直接选择"],
  // 업종(폰 MERCHANT_CATEGORY_NAMES)
  "음식": ["Food", "飲食", "餐饮"],
  "과일·채소": ["Fruit & vegetables", "果物・野菜", "水果·蔬菜"],
  "카페": ["Café", "カフェ", "咖啡馆"],
  "운동·체육관": ["Fitness & gym", "運動・ジム", "运动·健身房"],
  "생활": ["Everyday services", "生活", "生活"],
  "수리": ["Repair", "修理", "维修"],
  "배움": ["Learning", "学び", "学习"],
  "기타": ["Other", "その他", "其他"],
  // 동네(폰 areas.ts)
  "의왕시": ["Uiwang", "義王市", "义王市"],
  "의왕 내손동": ["Uiwang Naeson-dong", "義王 内蓀洞", "义王 内荪洞"],
  "의왕 부곡동": ["Uiwang Bugok-dong", "義王 富谷洞", "义王 富谷洞"],
  "안양 만안구": ["Anyang Manan-gu", "安養 萬安区", "安养 万安区"],
  "안양 동안구": ["Anyang Dongan-gu", "安養 東安区", "安养 东安区"],
  "군포시": ["Gunpo", "軍浦市", "军浦市"],
  "과천시": ["Gwacheon", "果川市", "果川市"],
  "수원 장안구": ["Suwon Jangan-gu", "水原 長安区", "水原 长安区"],
  "수원 권선구": ["Suwon Gwonseon-gu", "水原 勧善区", "水原 劝善区"],
  "수원 팔달구": ["Suwon Paldal-gu", "水原 八達区", "水原 八达区"],
  "수원 영통구": ["Suwon Yeongtong-gu", "水原 霊通区", "水原 灵通区"],
  "성남 수정구": ["Seongnam Sujeong-gu", "城南 寿井区", "城南 寿井区"],
  "성남 중원구": ["Seongnam Jungwon-gu", "城南 中院区", "城南 中院区"],
  "성남 분당구": ["Seongnam Bundang-gu", "城南 盆唐区", "城南 盆唐区"],
  "서울 강남구": ["Seoul Gangnam-gu", "ソウル 江南区", "首尔 江南区"],
  "서울 서초구": ["Seoul Seocho-gu", "ソウル 瑞草区", "首尔 瑞草区"],
  "서울 송파구": ["Seoul Songpa-gu", "ソウル 松坡区", "首尔 松坡区"],
  "서울 관악구": ["Seoul Gwanak-gu", "ソウル 冠岳区", "首尔 冠岳区"],
  "서울 동작구": ["Seoul Dongjak-gu", "ソウル 銅雀区", "首尔 铜雀区"],
  "서울 영등포구": ["Seoul Yeongdeungpo-gu", "ソウル 永登浦区", "首尔 永登浦区"],
  "서울 마포구": ["Seoul Mapo-gu", "ソウル 麻浦区", "首尔 麻浦区"],
  "서울 종로구": ["Seoul Jongno-gu", "ソウル 鍾路区", "首尔 钟路区"],
  "서울 용산구": ["Seoul Yongsan-gu", "ソウル 龍山区", "首尔 龙山区"],
  "서울 강서구": ["Seoul Gangseo-gu", "ソウル 江西区", "首尔 江西区"],
  "서울 노원구": ["Seoul Nowon-gu", "ソウル 蘆原区", "首尔 芦原区"],
};
