/** 설정 › 「폰 연결」(RV6) 문구 — 한국어 원문 → [영어, 일본어, 간체 중국어]. dict.ts 가 합친다. */
export const PAIRING_COPY: Record<string, [string, string, string]> = {
  "방금": ["Just now", "たった今", "刚刚"],
  "{0}분 전": ["{0} min ago", "{0}分前", "{0} 分钟前"],
  "{0}시간 전": ["{0} h ago", "{0}時間前", "{0} 小时前"],
  "{0}일 전": ["{0} days ago", "{0}日前", "{0} 天前"],
  "폰 연결": ["Phone link", "スマホ連携", "手机连接"],
  "폰으로 QR 을 찍으면, 폰에서 이 컴퓨터의 잔액·증서·매출을 보고 요청을 보낼 수 있어요.": ["Scan the QR with your phone to see this computer’s balance, certificates and sales, and to send requests from the phone.", "スマホで QR を読み取ると、このコンピュータの残高・証書・売上をスマホで見たり、依頼を送ったりできます。", "用手机扫描二维码后，即可在手机上查看这台电脑的余额、证书和销售额，并发送请求。"],
  "폰 지갑과 이 컴퓨터 지갑은 섞이지 않아요. 복구 단어와 개인키는 이 컴퓨터 밖으로 나가지 않아요.": ["The phone wallet and this computer’s wallet stay separate. Recovery words and private keys never leave this computer.", "スマホのウォレットとこのコンピュータのウォレットは混ざりません。復元単語と秘密鍵はこのコンピュータの外に出ません。", "手机钱包和这台电脑的钱包互不混用。助记词和私钥不会离开这台电脑。"],
  "폰 연결 QR 보이기": ["Show phone link QR", "スマホ連携 QR を表示", "显示手机连接二维码"],
  "폰에서: RavenVault 앱 › 「데스크톱 연결」 › QR 찍기": ["On the phone: RavenVault app › “Connect desktop” › scan the QR", "スマホで：RavenVault アプリ ›「デスクトップ連携」› QR を読み取る", "在手机上：RavenVault 应用 ›“连接电脑” › 扫描二维码"],
  "이 컴퓨터 확인 글자": ["This computer’s check code", "このコンピュータの確認コード", "这台电脑的核对码"],
  "QR 은 한 번만 쓸 수 있어요. 새로 띄우면 앞의 QR 은 못 써요.": ["The QR works only once. Showing a new one cancels the old one.", "QR は一度だけ使えます。新しく表示すると前の QR は使えません。", "二维码只能使用一次。显示新的二维码后，旧的将失效。"],
  "같은 Wi-Fi 로 바로 잇는 길이 꺼져 있어요. 「폰으로 보기」 서버가 켜져 있는지 확인해 주세요.": ["The direct same-Wi-Fi route is off. Check that the “View on phone” server is running.", "同じ Wi-Fi で直接つなぐ経路がオフです。「スマホで見る」サーバーが起動しているか確認してください。", "同一 Wi-Fi 直连通道已关闭。请确认“在手机上查看”服务器已开启。"],
  "QR 닫기": ["Close QR", "QR を閉じる", "关闭二维码"],
  "폰이 연결하려고 해요": ["A phone wants to connect", "スマホが接続しようとしています", "有手机请求连接"],
  "폰 화면의 숫자와 같을 때만 허락하세요. 다르면 거절하세요.": ["Allow only if this number matches the phone screen. If it differs, decline.", "スマホ画面の数字と同じときだけ許可してください。違う場合は拒否してください。", "仅当数字与手机屏幕一致时才允许。如果不同，请拒绝。"],
  "이 폰은 「요청」 권한도 원해요. 필요할 때만 켜 주세요.": ["This phone also wants “Request” permission. Turn it on only if needed.", "このスマホは「依頼」権限も求めています。必要なときだけオンにしてください。", "此手机还希望获得“请求”权限。仅在需要时开启。"],
  "이 폰이 할 수 있는 일": ["What this phone may do", "このスマホができること", "此手机可以做的事"],
  "보기 — 잔액·자산·증서·매출": ["View — balance, assets, certificates, sales", "表示 — 残高・資産・証書・売上", "查看 — 余额、资产、证书、销售额"],
  "요청 — 증서 만들기·손님 QR 띄우기·보내기 요청": ["Request — make certificates, show customer QR, ask to send", "依頼 — 証書作成・お客様 QR 表示・送金依頼", "请求 — 制作证书、显示顾客二维码、请求转账"],
  "돈이 나가는 일": ["Payments out", "お金が出ていくこと", "资金转出"],
  "이 컴퓨터에서 확인 (기본)": ["Confirm on this computer (default)", "このコンピュータで確認（既定）", "在这台电脑上确认（默认）"],
  "폰 승인 허용 — 하루 한도 안에서만": ["Allow phone approval — only within a daily limit", "スマホ承認を許可 — 1日の上限内のみ", "允许手机批准 — 仅限每日额度内"],
  "하루 한도 (RVN, 최근 24시간)": ["Daily limit (RVN, last 24 hours)", "1日の上限（RVN、直近24時間）", "每日额度（RVN，最近 24 小时）"],
  "폰 승인이어도 지갑이 잠겨 있으면 풀릴 때까지 기다려요. 자산 보내기는 언제나 이 컴퓨터에서 확인해요.": ["Even with phone approval, a locked wallet waits until it is unlocked. Asset transfers are always confirmed on this computer.", "スマホ承認でも、ウォレットがロック中なら解除されるまで待ちます。資産の送付は常にこのコンピュータで確認します。", "即使是手机批准，钱包锁定时也会等到解锁。资产转账始终在这台电脑上确认。"],
  "허락": ["Allow", "許可", "允许"],
  "거절하기": ["Decline", "拒否する", "拒绝"],
  "연결된 기기": ["Connected devices", "接続中の機器", "已连接的设备"],
  "폰 요청": ["Phone requests", "スマホからの依頼", "手机请求"],
  "폰이 보낸 요청은 24시간 기다려요. 열면 이 컴퓨터의 원래 화면으로 가요.": ["Requests from a phone wait for 24 hours. Opening one takes you to this computer’s usual screen.", "スマホからの依頼は24時間待ちます。開くとこのコンピュータのいつもの画面に移ります。", "手机发来的请求会保留 24 小时。打开后会进入这台电脑上的常用界面。"],
  "공개 Nostr 중계도 예비 통로로 쓰기 (기본 끔)": ["Also use public Nostr relays as a backup route (off by default)", "公開 Nostr リレーも予備経路として使う（既定はオフ）", "同时使用公共 Nostr 中继作为备用通道（默认关闭）"],
  "공개 중계는 내용은 못 보지만, 언제 어느 기기끼리 주고받는지는 볼 수 있어요.": ["Public relays cannot read the content, but they can see when and which devices exchange messages.", "公開リレーは内容を見られませんが、いつどの機器同士がやり取りしたかは見えます。", "公共中继无法查看内容，但可以看到何时、哪些设备之间在通信。"],
  "보기": ["View", "表示", "查看"],
  "요청": ["Request", "依頼", "请求"],
  "폰 승인": ["Phone approval", "スマホ承認", "手机批准"],
  "돈은 이 컴퓨터에서 확인": ["Payments confirmed on this computer", "送金はこのコンピュータで確認", "付款在这台电脑上确认"],
  "아직 연결된 폰이 없어요.": ["No phone is connected yet.", "まだ接続中のスマホはありません。", "还没有已连接的手机。"],
  "마지막 사용": ["Last used", "最終利用", "最近使用"],
  "연결 끊기": ["Disconnect", "接続を解除", "断开连接"],
  "기다리는 요청이 없어요.": ["No waiting requests.", "待機中の依頼はありません。", "没有等待中的请求。"],
  "열기": ["Open", "開く", "打开"],
  "폰 승인 보내기 — 지갑이 잠겨 있어 기다리는 중": ["Phone-approved send — waiting because the wallet is locked", "スマホ承認の送金 — ウォレットがロック中のため待機中", "手机批准的转账 — 钱包已锁定，正在等待"],
  "보내기 화면에서 확인하는 중": ["Being checked on the send screen", "送金画面で確認中", "正在转账界面确认"],
  "{0} · 남은 시간 {1}시간": ["{0} · {1} h left", "{0} · 残り {1} 時間", "{0} · 剩余 {1} 小时"],
  "{0}분 안에 허락하지 않으면 자동으로 거절돼요.": ["If not allowed within {0} min, it is declined automatically.", "{0}分以内に許可しないと自動的に拒否されます。", "如果 {0} 分钟内未允许，将自动拒绝。"],
  "남은 시간 {0}:{1}": ["Time left {0}:{1}", "残り時間 {0}:{1}", "剩余时间 {0}:{1}"],
  "보내기 화면에 채워 두었어요. 받는 주소와 금액을 다시 확인하고 보내세요.": ["The send screen has been filled in. Check the address and amount again, then send.", "送金画面に入力しておきました。受取アドレスと金額をもう一度確認してから送ってください。", "已填入转账界面。请再次确认收款地址和金额后再发送。"],
  "증서 만들기 요청": ["Certificate request", "証書作成の依頼", "制作证书请求"],
  "제목": ["Title", "タイトル", "标题"],
  "받는 사람": ["Recipient", "受取人", "接收人"],
  "장수": ["Copies", "枚数", "张数"],
  "메모": ["Memo", "メモ", "备注"],
  "사진·엑셀은 이 컴퓨터에서 붙여 주세요. 만들기 화면에서 평소처럼 확인하고 발행해요.": ["Attach photos and spreadsheets on this computer. Check and issue on the Create screen as usual.", "写真・Excel はこのコンピュータで添付してください。作成画面でいつも通り確認して発行します。", "请在这台电脑上添加照片和表格。在制作界面照常确认并发行。"],
  "만들기 화면으로": ["Go to Create", "作成画面へ", "前往制作界面"],
  "닫기": ["Close", "閉じる", "关闭"],
  "{0} 폰과 연결했어요.": ["Connected to {0}.", "{0} と接続しました。", "已连接 {0}。"],
  "거절했어요. 폰에는 연결이 안 돼요.": ["Declined. The phone is not connected.", "拒否しました。スマホは接続されません。", "已拒绝。该手机未连接。"],
  "이 폰과 연결을 끊을까요?": ["Disconnect this phone?", "このスマホとの接続を解除しますか？", "要断开这部手机吗？"],
  "끊으면 그 폰은 바로 아무것도 못 해요. 다시 쓰려면 QR 로 새로 연결해요.": ["Once disconnected, the phone can do nothing right away. To use it again, connect anew with a QR.", "解除するとそのスマホはすぐに何もできなくなります。再び使うには QR で新しく接続します。", "断开后该手机将立即无法执行任何操作。若要再次使用，请用二维码重新连接。"],
  "연결을 끊었어요.": ["Disconnected.", "接続を解除しました。", "已断开连接。"],
  "요청을 거절했어요. 폰에 알렸어요.": ["Request declined. The phone has been told.", "依頼を拒否しました。スマホに知らせました。", "已拒绝请求，并已通知手机。"],
  "폰이 연결을 기다려요 — 확인하기": ["A phone is waiting to connect — check", "スマホが接続を待っています — 確認する", "有手机在等待连接 — 查看"],
  "폰 요청 {0}건 — 보기": ["{0} phone requests — view", "スマホからの依頼 {0} 件 — 見る", "{0} 个手机请求 — 查看"],
  "보내기 요청": ["Send request", "送金依頼", "转账请求"],
  "손님 QR 띄우기": ["Show customer QR", "お客様 QR を表示", "显示顾客二维码"],
  // 이 컴퓨터(Rust)가 돌려주는 오류 문장
  "연결 기능을 켜지 못했어요.": ["Could not turn on phone linking.", "スマホ連携をオンにできませんでした。", "无法开启手机连接。"],
  "돈이 나가는 일의 방식을 다시 골라 주세요.": ["Choose how payments out are confirmed again.", "お金が出ていくときの方式をもう一度選んでください。", "请重新选择资金转出的确认方式。"],
  "하루 한도가 너무 커요.": ["The daily limit is too large.", "1日の上限が大きすぎます。", "每日额度过大。"],
  "허락할 수 있는 5분이 지났어요. 새 QR 로 다시 연결해 주세요.": ["The 5 minutes to allow have passed. Connect again with a new QR.", "許可できる5分が過ぎました。新しい QR でもう一度接続してください。", "允许的 5 分钟已过。请用新的二维码重新连接。"],
  "기다리는 연결 요청이 없어요. 새 QR 로 다시 연결해 주세요.": ["No connection request is waiting. Connect again with a new QR.", "待機中の接続依頼がありません。新しい QR でもう一度接続してください。", "没有等待中的连接请求。请用新的二维码重新连接。"],
  "연결 기능이 켜져 있지 않아요.": ["Phone linking is not on.", "スマホ連携がオンになっていません。", "手机连接未开启。"],
  "그 요청을 찾지 못했어요.": ["That request was not found.", "その依頼が見つかりませんでした。", "找不到该请求。"],
  "이미 처리한 요청이에요.": ["This request has already been handled.", "すでに処理した依頼です。", "该请求已处理。"],
  "거래 번호 모양이 아니에요.": ["That is not a transaction ID.", "取引番号の形式ではありません。", "这不是交易编号的格式。"],
};
